### ISSUE TITLE
[admin plugin] Plugin Management

### ISSUE THREAD

**Issue by ozon** [BigBrotherBot/big-brother-bot#143]
The Admin Plugin provides the commands `!enable <plugin>` and `!disable <plugin>`.
I think it makes more sense to merge these commands and possibly expand.

Why?
- The two existing commands are simple and treat incorrect inputs not useful. It is annoying when you type the command wrong and you do not get an overview right inputs.
- The user can not see what plugins he can manage.
- For both or more commands are different permissions. This is unnecessary.

I am in favor to implement the plugin administration over 1 command.
`!plugin <name> <action>`
Example:
`!plugin pingkicker disable` (Even "disable" be replaced by "stop" for easier typing,)
`!plugin pingkicker start`

`!plugin pingkicker` - If action is missing, then show the plugin status.
`!plugin list` - show a list of all plugins
`!plugin list <enabled/disabled>` - output a filtered list of plugins
`!plugin pingkicker info` - show stuff like `!pluginfo <plugin>`.

This is just an idea. What do you think?

**Comment by danielepantaleone** [comment]
Done in #310
