### ISSUE TITLE
Make the MySQL database use the InnoDB engine

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#16]
See forum [discussion](http://forum.bigbrotherbot.net/general-discussion/re-iourt41-py-1-11-5-error/)

Currently (B3 1.9b2) the MySQL database engine is MyISAM. The migration toward the InnoDB engine is motivated by administration concerns. Mainly :

- no dataloss when database server crashes
- hot backup without interruption of service

However migrating to the InnoDB engine involves changes to the B3 code :
- in the SQL scripts obviously
- in the python code that runs the SQL queries as the InnoDB engine supports transactions
- a migration script that would be able to upgrade an existing B3 database using the MyISAM engine

**Comment by danielepantaleone** [comment]
I'm closing this one since B3 now supports MySQL, SQLite and PostgreSQL and only MySQL supports InnoDB tables. If the main concern is dataloss, we could setup a B3 plugin which spawns a thread every X mins/hours that will handle database backup.
