### ISSUE TITLE
B3 main configuration file 

### ISSUE THREAD

**Issue by danielepantaleone** [BigBrotherBot/big-brother-bot#179]
I was thinking of porting also the b3.distribution.xml file to the INI format since the latest one is far more user friendly than XML. However this will introduce some limitations because the INI format contains key-value pairs while with the XML format is possible to specify several attributes for every document node.
If the change will be done some features will be missing (like loading plugins and disabled them on startup or specify a different path for a plugin module). 
Anyway, I did a preview of how the new configuration file should look like: https://gist.github.com/danielepantaleone/018528d401e0504bdc9e

Any thoughts?

**Comment by danielepantaleone** [comment]
Alright, template files have been updated to .ini format (https://github.com/danielepantaleone/big-brother-bot/commit/ebd8c1cd3baa6b054fdc6e86c52e13bc13502e94) and setup procedure now produces a .ini configuration file (https://github.com/danielepantaleone/big-brother-bot/commit/3ff79286efed3d1d90790786659e37d348e697f7)

What is left to be done before merging in release-1.10 branch?

**Comment by thomasleveil** [comment]
regarding B3 it seems fine. We would have to provide a new version of http://config.bigbrotherbot.net/. See https://github.com/ozguruysal/b3-config-generator/issues/13

**Comment by danielepantaleone** [comment]
Since B3 will still support xml format as main configuration file, won't be better to merge the branch anyway (to reduce conflicts everytime I have to merge `release-1.10` into the `new-configuration` branch).

**Comment by thomasleveil** [comment]
Sure, make a PR. B3 needs to go forward ;)

**Comment by ozguruysal** [comment]
@danielepantaleone  we also would like to hear your ideas at https://github.com/ozguruysal/b3-config-generator/issues/14 when you have time.

**Comment by danielepantaleone** [comment]
I'll close this one, since on B3 side everything has been done
