### ISSUE TITLE
[STORAGE] missing context manager decorated query method

### ISSUE THREAD

**Issue by danielepantaleone** [BigBrotherBot/big-brother-bot#240]
I have been messing a bit with contextlib recently and I thought about extending the current `DatabaseStorage.query` method with a `@contextmanager` decorator (actually make a new method not to break backwards compatibility). So I produced this: https://gist.github.com/danielepantaleone/5a81f9863eececd67a4e

The good things of this implementation is that we can make use of the `with` statement when executing queries which are supposed to return values, and thus ensure that the cursor is getting closed whenever the execution goes out of the `with` statement block. Example:

```python
names = []
with self.console.storage.context_query("""SELECT * FROM clients""") as cursor:
    if cursor.EOF:
        self.debug('clients table empty')
    while cursor.moveNext():
        names.append(cursor.getValue('name'))
## HERE CURSOR IS CLOSED
```

Now, I tried to implement this in B3 and produced some tests that confirmed it to be working good. But here it comes the problem: when I replaced the usage of `query` with `context_query` in B3 files, 38 tests were failing. The problem was not the `context_query` implementation, but more the `query` one (which I think behaves strangely). The `query` method returns `None` whenever the database connection fails and imho this is an error, since `query` should just throw back an exception which would need to be handled above. The `context_query` doesn't return a value since it makes use of the `yield` keyword to hold the result till we need it (and then process the closing of the cursor) and this I cannot emulate the return `None` (which, once again, I believe is wrong placed). 

My question is: at current state what happens when `query` cannot initialize a valid database connection (and thus return `None`) and at top layer (for example in a plugin) this return value is not checked to be != `None` (and I saw that it's plenty of this cases in B3 files, especially in storage module). It should depend on where the `AttributeError` exception is catched (if it's catched, but I assume that it's not), but eventually this could crash B3.

**Comment by thomasleveil** [comment]
See my comment on #246.
Is your question regarding PostgreSQL still applicable since you included the PostgreSQL code in your PR?

**Comment by danielepantaleone** [comment]
I solved the PostgreSQL problem. Basically the ``QueryBuilder`` class was using double quotes to quote arguments during query generation. While this is correct for MySQL and SQLite, it's not accepted by PostgreSQL which requires single quotes to be used. Making the changes globally was causing troubles in single quotes escaping, so I patched the ``QueryBuilder.escape`` method at runtime (https://github.com/danielepantaleone/big-brother-bot/blob/release-1.10/b3/storage/postgresql.py#L255) when the PostgreSQL storage module is being used.

PostgreSQL also doesn't support backticks (used to quote column names). I fixed it by stripping them out before executing the query (https://github.com/danielepantaleone/big-brother-bot/blob/release-1.10/b3/storage/postgresql.py#L201) but probably we could make use of the db instance stored in the ``QueryBuilder`` to choose what action to take (surround with backticks or not). Both solutions would work though.

**Comment by thomasleveil** [comment]
what about a query which tries to insert a player alias having a backtick in the value itself?

**Comment by danielepantaleone** [comment]
It seems that I have some work to do :smile: good catch :+1:

**Comment by danielepantaleone** [comment]
Now I remember why I chose to strip them out from the query: not all the plugins make use of the `QueryBuilder` and so removing backticks from there only won't solve the problem. I think the best option would be to use a regular expression to identify backticks which are actually surrounding an argument (and are not in the middle of a string)

**Comment by thomasleveil** [comment]
Maybe there is a python module which is able to produce an abstract syntax tree for sql. This would ease making the difference between backticks as syntax or as value
