### ISSUE TITLE
Plugin module structure

### ISSUE THREAD

**Issue by danielepantaleone** [BigBrotherBot/big-brother-bot#247]
At current state plugin modules are composed by either a single python file or a directory containing one or more python files (some external plugins like: https://github.com/thomasleveil/b3-plugin-poweradminurt, https://github.com/danielepantaleone/b3-plugin-ircbot, ...). I think it would be better to have a unique structure for plugins (which won't affect backwards compatibility). While this may sound silly for people knowing how the python programming language works, it may be very helpful for end users who have to install plugins (since installing a plugin will require the very same steps if we enforce a unique module structure) and maybe it would be possible to make B3 able to install plugins automatically (I tried in the past and I still have this in mind). What I want to suggest is something like this:

```
b3
---- plugins
-------- modulename                              ##### plugin module
------------ __init__.py                         ##### plugin main class goes here
------------ optionalpythonfile.py
------------ someotheroptionalpythonfile.py
------------ sql                                 ##### SQL scripts for generating/updating database
---------------- mysql
-------------------- modulename.sql
-------------------- modulename-update-1.1.2.sql
---------------- sqlite
-------------------- modulename.sql
-------------------- modulename-update-1.1.2.sql
---------------- postgresql
-------------------- modulename.sql
-------------------- modulename-update-1.1.2.sql
```

This will imply moving built-in plugins into the new structure and implementing #25

**Comment by thomasleveil** [comment]
I don't see any drawback to more normalization, sounds good to me.
