### ISSUE TITLE
[UPDATER] add backup utility

### ISSUE THREAD

**Issue by danielepantaleone** [BigBrotherBot/big-brother-bot#253]
I leave this just as a memo. Apparently on some *weird* configurations the updater plugin is failing in upgrading B3. We would need to setup a backup utility that restores the previously working B3 upon update failure.

**Comment by thomasleveil** [comment]
there is the [esky](https://pypi.python.org/pypi/esky) python module which should provide such mechanism, but I'm not sure if the whole esky stuff is applicable to B3. The interesting thing about esky is that it deals with _frozen_ images of the app which implies that it would work with our Windows distribution of B3

**Comment by danielepantaleone** [comment]
Which makes me think: won't be better to distribute B3 as Frozen application also for Linux systems and OSX? Since the Win32 bin is already capable of loading external plugins we can make the Linux app do the same. I think it would be way easier for end users to deal with a binary file instead of B3 sources. Advanced users then can still run it from sources if they need. Is there any particular reason why not to?

**Comment by thomasleveil** [comment]
I see no reason, but it means more work on us as we are adding a new distribution.

**Comment by danielepantaleone** [comment]
That is true, but we can eventually automate the build procedure. Say night at time X, a cronjob package a daily build and push it on the download section of the server. It shouldn't be hard to do, and in this way you do not have to take care of pushing daily builds manually

**Comment by danielepantaleone** [comment]
I'll open a new issue to discuss the matter: #254

**Comment by danielepantaleone** [comment]
Done here: https://github.com/BigBrotherBot/big-brother-bot/commit/1f2ecebcc11da6cd4ca2306ce1381fee657eb538
