### ISSUE TITLE
[XLRSTATS] Unkown column 'None' for CS:GO and Insurgency

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#273]
as @zdanman [reported](https://github.com/BigBrotherBot/big-brother-bot/issues/201#issuecomment-72977634)

see #9 #201

> This still doesnt work for CSGO or Insurgency.
> 
> latest xlrstats:
> https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/extplugins/xlrstats/__init__.py
> 
> `self.console.clients.getByGUID("WORLD")`
> returns `None`
> 
> and 
> 
> `self.console.clients.getByGUID("Server")`
> returns `None`
> 
> therefore `sclient` and `self._world_clientid` stay as `None`
> 
> therefore on [line 1708](https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/extplugins/xlrstats/__init__.py#L1708) (in v3.0.0 beta 11) it fails because it shoots a invalid SQL query with columns name None because it uses `_world_clientid`.
> 
> Please fix.

```
150204 19:21:50	ERROR	'Query failed [SELECT MAX(`xlr_playerstats`.skill) AS max_skill, MIN(`xlr_playerstats`.skill) AS min_skill, SUM(`xlr_playerstats`.skill) AS sum_skill,\n               AVG(`xlr_playerstats`.skill) AS avg_skill , COUNT(`xlr_playerstats`.id) AS cnt\n               FROM xlr_playerstats, clients\n               WHERE `clients`.id = `xlr_playerstats`.client_id\n               AND `xlr_playerstats`.client_id <> None\n               AND (`xlr_playerstats`.kills + `xlr_playerstats`.deaths) > 50\n               AND 1423099310 - `clients`.time_edit <= 5184000] None: (1054, u"Unknown column \'None\' in \'where clause\'")'
150204 19:21:50	ERROR	'Could not start plugin xlrstats'
Traceback (most recent call last):
  File "b3\parser.pyo", line 995, in startPlugins
  File "b3\parser.pyo", line 988, in start_plugin
  File "b3\plugin.pyo", line 335, in onStartup
  File "C:\bluefang\servers\server1876\extplugins\xlrstats.py", line 308, in startup
  File "C:\bluefang\servers\server1876\extplugins\xlrstats.py", line 1723, in correctStats
  File "b3\storage\common.pyo", line 633, in query
InternalError: (1054, u"Unknown column 'None' in 'where clause'")
```

**Comment by danielepantaleone** [comment]
Seems that the WORLD (or Server) client is not created in both parsers. I'll fix it in a PR.

**Comment by danielepantaleone** [comment]
I actually noticed a strange behaviour here: in some parsers the WORLD client is being saved in the storage and in some other parsers it's not (or should not be since the `hide` flag is set but B3 ignores it). What should be the correct behaviour?

**Comment by zdanman** [comment]
as a temporary fix i deleted the lines 1707 and 1714.  of course this only works for insurgency and is only temporary until official fixed.

**Comment by zdanman** [comment]
as a temporary fix i deleted the lines 1707 and 1714.  of course this only works for insurgency and is only temporary until official fixed.

**Comment by zdanman** [comment]
as a temporary fix i deleted the lines 1707 and 1714.  of course this only works for insurgency and is only temporary until official fixed.

**Comment by danielepantaleone** [comment]
The problem is not in the XLRstats plugin but in the CS:GO and Insurgency parsers. I already have a fix for this but I need an answer for this: https://github.com/BigBrotherBot/big-brother-bot/issues/273#issuecomment-73023500 in order to adapt test cases.

**Comment by thomasleveil** [comment]
IIRC the WORLD client exists only to act as the killer for kill induced by the game environment (drowning, falling, etc).
I'm tempted to think that such a client must exists for each parser.
Anyway it should not harm to add it, so I would add it if missing.

Am I answering all your questions?

**Comment by danielepantaleone** [comment]
Alright, I know what to do

**Comment by zdanman** [comment]
Any update on this?

**Comment by danielepantaleone** [comment]
Alright, I added the 'Server' client in both parsers: https://github.com/danielepantaleone/big-brother-bot/commit/b56043ba7ad3d4aac4a03dab29f03581149b360c
I didn't update test cases because it seems that they were already considering the Server client (but it was not created by the paser), so I'm quite confused. Here an example:

```python
def test_known_client_by_cid(self):
        # GIVEN
        known_client = Client(console=self.parser, guid="AAAAAAAAAAAA000000000000000", name="theName")
        known_client.save()
        self.assertEqual(1, len(self.parser.clients)) # THIS IS OK SINCE WE HAVE 1 CLIENT
        self.assertDictContainsSubset({'clients': 2}, self.parser.storage.getCounts()) # THIS SHOULD BE 1 (THERE WAS NO SERVER CLIENT SO WHY 2???
        # WHEN
        client = self.parser.getClientOrCreate(cid="2", guid="AAAAAAAAAAAA000000000000000", name="newName", team="CT")
        # THEN
        self.assertIsInstance(client, Client)
        self.assertEqual(known_client.id, client.id)
        self.assertEqual("2", client.cid)
        self.assertEqual("AAAAAAAAAAAA000000000000000", client.guid)
        self.assertEqual("newName", client.name)
        self.assertEqual(TEAM_RED, client.team)
        self.assertTrue(client.authed)
        self.assertEqual(2, len(self.parser.clients)) # THIS SHOULD BE 1: GUID IS THE SAME SO PARSER SHOULD NOT CREATE A NEW CLIENT
        self.assertDictContainsSubset({'clients': 2}, self.parser.storage.getCounts()) # SAME AS ABOVE
```

Comments in CAPS are my thoughts. I could have updated those numbers increasing them by one but I don't think it's the correct approach since I don't know where those numbers come from. @thomasleveil could give a loop please?

**Comment by thomasleveil** [comment]
I'll take a look tonight, thank you for highlighting this

**Comment by danielepantaleone** [comment]
This is getting even more weird: I added a snippet in the test function which retrieve all the clients from the database, and apparently there is only the server client (since the BOT is not saved....actually should not be saved but I found nothing preventing the saving, but w/e). But then after the query result being printed, the count of the clients returns 2

```
======================================================================
FAIL: test_bot_connected (tests.parsers.test_csgo.Test_gamelog_parsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Daniele\workspace\big-brother-bot\tests\parsers\test_csgo.py", line 405, in test_bot_connected
    self.assertDictContainsSubset({'clients': 1}, self.parser.storage.getCounts())
AssertionError: Mismatched values: 'clients', expected: 1, actual: 2
-------------------- >> begin captured stdout << ---------------------
password - 
time_add - 1423304728
name - Server
group_bits - 0
ip - 
auto_login - 1
pbid - Server
connections - 1
time_edit - 1423304728
mask_level - 0
login - 
guid - Server
id - 1
greeting - 

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 0.017s

FAILED (failures=1)
```

**Comment by thomasleveil** [comment]
That player is 'Courgette' and it's there because of https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/tests/parsers/test_csgo.py#L34

**Comment by danielepantaleone** [comment]
Yes but that doesn't explain why if I do `SELECT * FROM clients` I obtain 1 record only, but if I do `SELECT count(id) total FROM clients` I obtain 2. Or am I missing something here..

**Comment by thomasleveil** [comment]
There must be something wrong with the way you run the query, try the following modified `test_bot_connected` method:

```python
    def test_bot_connected(self):
        # GIVEN
        self.assertIsNone(self.parser.clients.getByCID("3"))
        # WHEN
        self.clear_events()
        self.parser.parseLine('''L 08/26/2012 - 03:22:36: "Moe<3><BOT><>" connected, address "none"''')
        # THEN a client object is created
        client = self.parser.clients.getByCID("3")
        self.assertIsNotNone(client)
        self.assertTrue(client.bot)
        self.assertEqual("Moe", client.name)
        self.assertEqual('BOT3', client.guid)
        self.assertEqual("", client.ip)
        # THEN events are fired
        self.assert_has_event("EVT_CLIENT_CONNECT", data=client, client=client)
        self.assert_has_not_event("EVT_CLIENT_AUTH", data=client, client=client)
        # THEN no client object is saved to database
        clients_from_storage = self.parser.storage.getClientsMatching({'%name%': 'Moe'})
        self.assertListEqual([], clients_from_storage)
        self.assertDictContainsSubset({'clients': 1}, self.parser.storage.getCounts())

        cursor = self.parser.storage.query("select * from clients")
        while not cursor.EOF:
            print "\nROW: ", cursor.getRow()
            cursor.moveNext()
        cursor.close()

        Client.__repr__ = lambda x: "Client<@%s:%s|%s:\"%s\":%s>" % (x.id, x.guid, x.pbid, x.name, x.cid)
        print "\n\nself.parser.storage.getClientsMatching({}) :", self.parser.storage.getClientsMatching({})
        raise AssertionError
```

I then have `
```
-------------------- >> begin captured stdout << ---------------------

ROW:  {'password': u'', 'time_add': 1423311571, 'name': u'courgette', 'group_bits': 0, 'ip': u'', 'auto_login': 1, 'pbid': u'', 'connections': 1, 'time_edit': 1423311571, 'mask_level': 0, 'login': u'', 'guid': u'STEAM_1:0:1111111', 'id': 1, 'greeting': u''}


self.parser.storage.getClientsMatching({}) : [Client<@1:STEAM_1:0:1111111|:"courgette":None>]

--------------------- >> end captured stdout << ----------------------
```

which is all fine

**Comment by danielepantaleone** [comment]
I found the problem....in the test there were 2x `self.assertDictContainsSubset({'clients': 1}, self.parser.storage.getCounts())`

I tought I deleted one line but actually I just wrote between the 2 and modified only the first, and the second was then failing...shame on me :smile:

**Comment by zdanman** [comment]
Is this issue official resolved then with danieles latest commits?
Unkown column 'None' for CS:GO and Insurgency

Will it be added to the 1.10 Release?

**Comment by danielepantaleone** [comment]
Seems that the problem was the Server client not being generated so PR #279 should fix the problem. You'll be able to check when the next daily build will be released.

**Comment by thomasleveil** [comment]
available in [B3 daily build 309](http://files.cucurb.net/b3/daily/)
