### ISSUE TITLE
B3.altitude_example.xml is really needed?

### ISSUE THREAD

**Issue by danielepantaleone** [BigBrotherBot/big-brother-bot#287]
I always noticed that in the `b3/conf` directory there is this configuration file https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/conf/b3.altitude_example.xml. Since now all the parsers have a .tpl file to be used with the setup procedure, can't we remove it? Or is it needed for something else?

**Comment by thomasleveil** [comment]
we can remove it, anyway it will stay in the [altitude branch](https://github.com/BigBrotherBot/big-brother-bot/tree/altitude) which is the branch holding the code for the parser tutorial.

**Comment by danielepantaleone** [comment]
What I meant is: what makes this game different from the others? I don't have a b3.urban_terror42.xml in my conf folder for example :smiley: just out of curiosity :tongue:

**Comment by thomasleveil** [comment]
This file is mentioned in the tutorial IIRC
