### ISSUE TITLE
[TIMEZONE] detect timezone from system

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#297]
Setting the correct timezone in the B3 config file is a pain, why can't B3 detect the timezone from the machine it runs on?

I suggest we explore:
- how to autodetect the timezone offset
- let the current timezone list as it is to avoid complaints from existing users
- add `auto` to the list of current timezones to specifically tell B3 to autodetect
- make the `time_zone` setting optional and fallback on `auto` is missing
- add `INFO` message to _b3.log_ informing about the actual timezone B3 will use and its offset in hour

related reading:
- [Python time module](https://docs.python.org/2/library/time.html)
- [Python datetime module](https://docs.python.org/2/library/datetime.html#module-datetime)
- [pytz module](http://pytz.sourceforge.net/)
- an example of [using pytz](http://swizec.com/blog/handling-timezones-in-python/swizec/2835)

**Comment by danielepantaleone** [comment]
I totally agree with this. But this approach the user is still required to enter some data in the configuration file (according to some predefined format (like Europe/Paris, Europe/Berlin etc). Or if we want to get this value from the system we also have to consider that it may not be correct. 
What about, instead, setting up an GeoLocalization API using [MaxMind GeoIP2 database](http://dev.maxmind.com/geoip/geoip2/geolite2/). We could make B3 query the API using the server IP, and extract from the response the geolocalized timezone value.

We could setup a subdomain (i.e: api.bigbrotherbot.net) and create a PHP script which will do the job.

**Comment by thomasleveil** [comment]
> Or if we want to get this value from the system we also have to consider that it may not be correct. 

hence B3 writing to b3.log which tz it detected + the ability to override the detection by specifying a tz in the b3 config file

> GeoLocalization API using MaxMind GeoIP2 database

interesting but B3 would have to rely on an external service to get the correct tz. I'm uneasy with that idea. However this is a great idea for showing the time to each player tz! Players on a game server can be on a different tz as the one of the server, that would be a great improvement to the users XP :cake:

**Comment by danielepantaleone** [comment]
> Players on a game server can be on a different tz as the one of the server, that would be a great improvement to the users XP
I'm not sure I understood correctly. So you would like each in-game player to see time values in a different format (the correct one according to their timezone)?

**Comment by thomasleveil** [comment]
yes. I don't know how many commands display time but there is at least the !time command ;)

**Comment by danielepantaleone** [comment]
That could be achieved only for parsers which provide a private message command (some games iirc doesn't). Also we could just make a plugin for that. It's plenty of plugins which adds geolocation capabilities to B3 (GeoWelcome, CountryFilter, Location). We could just make a plugin on top of one of those and dynamically modify the admin plugin !time command.

**Comment by thomasleveil** [comment]
you right that would be safer.

anyway back on the server local time the following code does a great job at giving me the right time according to my tz:

    import datetime
    datetime.datetime.now()

**Comment by danielepantaleone** [comment]
Same on my systems. Well, then we know what to do :smiley:

**Comment by thomasleveil** [comment]
available in [B3 dev build 338](http://files.cucurb.net/b3/daily/)

**Comment by Yascor** [comment]
Hey, B3 release-1.10 from today.
Timezone detection working but time is not changed.
In b3.ini:
>parser: iourt42
time_format: %Y-%m-%d %H:%M (%Z)
time_zone: AUTO

In log:
>150514 23:23:35	VERBOSE	'Queueing event Say : !time'
150514 23:23:35	VERBOSE	'Parsing event: Say: AdminPlugin'
150514 23:23:35	DEBUG	'AdminPlugin: OnSay handle 9:"!time"'
150514 23:23:35	DEBUG	'AdminPlugin: handle command !time'
150514 23:23:35	DEBUG	'Auto detecting timezone information...'
150514 23:23:35	INFO	'Using timezone: CEST : 2.0'
150514 23:23:35	DEBUG	'Formatting time with timezone [CEST], tzOffset : 2.0'
150514 23:23:35	VERBOSE	"RCON sending (127.0.0.1:1234) 'tell 0 ^8[pm]^7 At the sound of the beep it will be ^32015-05-14 21:23 (CEST)^7...(beeeep)'"
150514 23:23:35	VERBOS2	'Say event handled by AdminPlugin in 2.593 ms'
150514 23:23:36	VERBOS2	"RCON: received ''"

with:
>time_zone: CEST

log:
>150514 23:33:30	VERBOSE	'Parsing event: Say: AdminPlugin'
150514 23:33:30	DEBUG	'AdminPlugin: OnSay handle 9:"!time"'
150514 23:33:30	DEBUG	'AdminPlugin: handle command !time'
150514 23:33:30	INFO	'Using timezone: CEST : 2'
150514 23:33:30	DEBUG	'Formatting time with timezone [CEST], tzOffset : 2'
150514 23:33:30	VERBOSE	"RCON sending (127.0.0.1:1234) 'tell 0 ^8[pm]^7 At the sound of the beep it will be ^32015-05-14 21:33 (CEST)^7...(beeeep)'"
150514 23:33:30	VERBOS2	'Say event handled by AdminPlugin in 1.587 ms'
150514 23:33:30	VERBOS2	"RCON: received ''"

with:
>time_zone: CET

log:
>150514 23:41:44	VERBOSE	'Parsing event: Say: AdminPlugin'
150514 23:41:44	DEBUG	'AdminPlugin: OnSay handle 9:"!time"'
150514 23:41:44	DEBUG	'AdminPlugin: handle command !time'
150514 23:41:44	INFO	'Using timezone: CET : 1'
150514 23:41:44	DEBUG	'Formatting time with timezone [CET], tzOffset : 1'
150514 23:41:44	VERBOSE	"RCON sending (127.0.0.1:1234) 'tell 0 ^8[pm]^7 At the sound of the beep it will be ^32015-05-14 21:41 (CET)^7...(beeeep)'"
150514 23:41:44	VERBOS2	'Say event handled by AdminPlugin in 1.958 ms'
150514 23:41:45	VERBOS2	"RCON: received ''"

**Comment by danielepantaleone** [comment]
Hmmm, i'll have a look

**Comment by danielepantaleone** [comment]
Fixed: https://github.com/BigBrotherBot/big-brother-bot/commit/7b15c408dd030c6890d222323138957d91f6f15f
