### ISSUE TITLE
fix pip install <url for b3 sources>

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#300]
since the recent switch to cx_freeze as a build solution, building and installing b3 from sources using pip isn't working anymore.

For instance, try in a new virutalenv:

    pip install https://github.com/BigBrotherBot/big-brother-bot/archive/release-1.10.zip

There are 2 issues:
- the need for cx_freeze to build from sources
- missing b3.egg-info directory

the branch [fix/cx_freeze](https://github.com/BigBrotherBot/big-brother-bot/tree/fix/cx_freeze) is an attempt to fix that.

**Comment by danielepantaleone** [comment]
It doesn't work here.

```
C:\Users\Daniele\workspace\big-brother-bot>python setup.py release
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'executables'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_exe'
```

That'e because you check for `build_exe` to be in `sys,argv` but when I execute `python setup release`  there is no `buiild_exe` in `sys,argv` since the arguments are in `setup.cfg` which is going to be parsed later

**Comment by thomasleveil** [comment]
Maybe we could forget about using setup.cft aliases for building the frozen packages. What do you think?

**Comment by danielepantaleone** [comment]
Or we can trick it: when running setup.py, parse setup.cfg manually, then check if the argument in sys.argv matches an alias: if so, modify sys.path.

Inviato da iPhone

**Comment by thomasleveil** [comment]
What we have to keep in mind is that `python setup.py build` must buld the py release by convention. Tools such as easy_setup and pip expect that behavior. Other than that we can do whatever we want. Also not being able to use the aliases from setup.cfg is not a big loss as there aren't necessary in the first place but just a bit of icing on the cake.
For those reasons I think it would be a pity to introduce even more hacks just for those aliases

**Comment by danielepantaleone** [comment]
I tried this simple snippet and it works pretty fine actually. It is tricky in the sense that it parse the setup.cfg and manipulate sys.argv, but the achieved result is the same of letting setuptools/cx_Freeze parse the setup.cfg file. 

```python
if len(sys.argv) > 1:
    if os.path.isfile(os.path.join(PROJECT_DIR, 'setup.cfg')):
        config = ConfigParser()
        config.read(os.path.join(PROJECT_DIR, 'setup.cfg'))
        for k in config.options('aliases'):
            if sys.argv[1] == k:
                options = config.get('aliases', k).split()
                sys.argv = sys.argv[1:] + options
                break
```

I'm hitting another issue right now though:

```
Traceback (most recent call last):
  File "setup.py", line 424, in <module>
    executables=executables
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 362, in setup
    distutils.core.setup(**attrs)
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 163, in run
    build_exe.run(self)  # call original build_exe run method
  File "C:\Python27\lib\site-packages\cx_Freeze\dist.py", line 232, in run
    freezer.Freeze()
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 621, in Freeze
    self._FreezeExecutable(executable)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 211, in _FreezeExecutable
    self._AddVersionResource(exe.targetName)
  File "C:\Python27\lib\site-packages\cx_Freeze\freezer.py", line 150, in _AddVersionResource
    stamp(fileName, versionInfo)
  File "C:\Python27\lib\site-packages\win32\lib\win32verstamp.py", line 123, in stamp
    raise ValueError("--version must be a.b.c.d (all integers) - got %r" % ver)
ValueError: --version must be a.b.c.d (all integers) - got '1.10.0-.0'
```

**Comment by thomasleveil** [comment]
have you run `python setup.py egg_info`?

**Comment by danielepantaleone** [comment]
I ran `python setup.py release` and the `egg_info` command is specified in the alias. The `b3.egg-info` directory has been generated correctly and I examined sys.argv which resulted to be:

``` 
C:\Users\Daniele\workspace\big-brother-bot>python setup.py release
['release', 'clean', 'egg_info', '-Db', '""', 'build_exe', 'bdist_egg', 'sdist', 'clean']
running clean
removing 'C:\Users\Daniele\workspace\big-brother-bot\b3.egg-info' (and everything under it)
running egg_info
creating b3.egg-info
writing b3.egg-info\PKG-INFO
writing top-level names to b3.egg-info\top_level.txt
writing dependency_links to b3.egg-info\dependency_links.txt
writing entry points to b3.egg-info\entry_points.txt
writing manifest file 'b3.egg-info\SOURCES.txt'
warning: manifest_maker: standard file 'release' not found

reading manifest file 'b3.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'b3\sql\*.sql'
warning: no previously-included files found matching '.idea\*'
writing manifest file 'b3.egg-info\SOURCES.txt'
```

**Comment by thomasleveil** [comment]
and is there anything fishy regarding the version number in the file b3.egg-info/PKG-INFO?

**Comment by danielepantaleone** [comment]
It has a dash at the end:

```
Metadata-Version: 1.1
Name: b3
Version: 1.10.0-
Summary: BigBrotherBot...
```

**Comment by thomasleveil** [comment]
is it only when calling `python setup.py release` or do you get that dash also when calling `python setup.py clean egg_info -Db "" build_exe bdist_egg sdist clean`?

It might be worth trying `python setup.py clean egg_info build_exe bdist_egg sdist clean`

**Comment by danielepantaleone** [comment]
using `python setup.py clean egg_info build_exe bdist_egg sdist clean` works perfectly...so I believe my little trick didn't work as expected. Well then we can give up on the `setup.cfg` file and use command line options

**Comment by thomasleveil** [comment]
ok then, I'll clean up this branch and merge later on
