### ISSUE TITLE
b3_run.exe is not killed if the B3 GUI is closed using the red [X] button

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#330]
using http://files.cucurb.net/b3/daily/b3-1.10.0.dev381-20150521-win32.zip if you close the windows using the [x] button on the top right corner, then the window disapear but the b3_run.exe process remains if you look in the Windows tasks manager.

closing the application with `File→Quit` or the `Quit` button on the bottom right corner does kill the process correctly.

![image](https://cloud.githubusercontent.com/assets/42300/7758289/e84a6a14-0008-11e5-8a83-8759f4204cde.png)

**Comment by danielepantaleone** [comment]
This is the expected behaviour. The system tray icon remains active. You can right click it to bring up the context menu, or double click it to show the main window again. Maybe I can show a ballon saying: B3 is still active

Inviato da iPhone

**Comment by thomasleveil** [comment]
This is not the convention on Windows. No other Windows program does this and it is quite confusing for the user. Can't this behavior be bound to the reduce button instead?

![image](https://cloud.githubusercontent.com/assets/42300/7758825/e3c26664-000c-11e5-8904-39fd56eae474.png)

**Comment by danielepantaleone** [comment]
Yeah sure. I can do this for windows and keep the current behavior for OSX (I'm not very familiar with windows ^^)

Inviato da iPhone

**Comment by danielepantaleone** [comment]
Done in https://github.com/BigBrotherBot/big-brother-bot/commit/e82686c22f4e4fcad0c830b750888ce23b471eec

**Comment by thomasleveil** [comment]
fixed :+1:
