### ISSUE TITLE
B3 GUI fails to start properly if installed in a directory that name has accentuated characters

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#331]
Download http://files.cucurb.net/b3/daily/b3-1.10.0.dev381-20150521-win32.zip and unzip it under `c:\tést\`. Run `b3_run.exe`. Images won't show up and the application is not working.

![image](https://cloud.githubusercontent.com/assets/42300/7758373/705261b4-0009-11e5-9a81-701c479ee80f.png)

**Comment by danielepantaleone** [comment]
Seems that you found the problem :)

Inviato da iPhone

**Comment by danielepantaleone** [comment]
I tested this on OSX and it works properly, I'll test also on Windows later. I think the solution is simply convert to unicode all the needed file paths.

**Comment by danielepantaleone** [comment]
Fixed in https://github.com/BigBrotherBot/big-brother-bot/commit/3dace2a909186067d6d3f6d15b9b90190d3077ef

**Comment by danielepantaleone** [comment]
@thomasleveil can you double check on your system that this actually works? And also verify if the fix for #330 works as supposed to?

**Comment by thomasleveil** [comment]
fixed! nice work :+1:
