### ISSUE TITLE
B3 fails to start the config wizard

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#333]
with daily383:

![image](https://cloud.githubusercontent.com/assets/42300/7787747/c7d3042e-021c-11e5-914d-25de4740c743.png)

The command run is `C:\BigBrotherBot\b3_run.exe --config "C:\BigBrotherBot\conf\b3.ini" --setup`

**Comment by thomasleveil** [comment]
This link could be replaced with http://config.bigbrotherbot.net/

**Comment by danielepantaleone** [comment]
Alright, I'll do this in the evening
