### ISSUE TITLE
B3 1.10dev402 fails to start on Windows

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#337]
when running b3_run.exe we can see the B3 logo while starting up, then an error message: `IndexError: No item with that key`

![2015-06-03_22h07_05](https://cloud.githubusercontent.com/assets/42300/7970291/3d9e099c-0a3d-11e5-8ec1-bf41bdf80d61.png)

**Comment by danielepantaleone** [comment]
Can you please delete app.db in home folder and restart b3? I did not included a sql update script since no one except us is using the GUI version at the moment. 

Inviato da iPhone

**Comment by thomasleveil** [comment]
that did the trick, but I have to add again my B3 instances

**Comment by danielepantaleone** [comment]
Yes, since they are stored in the db. After we release it, whenever i have to change db schema i will provide update scripts. 

Inviato da iPhone

**Comment by thomasleveil** [comment]
take a look at http://flywaydb.org/, it might be a great opportunity to learn that tool and profit from its sql upgrade managament system

**Comment by danielepantaleone** [comment]
I will look into it

Inviato da iPhone
