### ISSUE TITLE
[SQLITE] cursor.rowcount is not reliable

### ISSUE THREAD

**Issue by danielepantaleone** [BigBrotherBot/big-brother-bot#338]
I have been experiencing some troubles when creating test cases for the NickregPlugin. The plugin code was using `cursor.rowcount` to count the number of entries retrieved from the storage, but the `cursor.rowcount` value was always set to `-1`, no matter the amount of records retrieved. I fixed the problem using a SELECT COUNT(*)` query but this would need to be investigated: https://docs.python.org/2/library/sqlite3.html#sqlite3.Cursor.rowcount

**Comment by thomasleveil** [comment]
from that doc it seems the issue is in the implementation of the sqlite lib (on which python has no control, I guess it depends on the operating system sqlite is installed on).
The `SELECT COUNT(*)` is reliable in all cases, then IMHO we should use it.

**Comment by danielepantaleone** [comment]
My concern is more related to extplugins which are using it (Nickreg was one of them). 

Inviato da iPhone
