### ISSUE TITLE
[IOURT42] client.team returns "-1"

### ISSUE THREAD

**Issue by Yascor** [BigBrotherBot/big-brother-bot#340]
Hey, time ago I wrote simple plugin and few extra things based on "client.team" for my jump server, something like:
>
        if client.team == b3.TEAM_SPEC:
            self.console.write("forceteam %s a" % (client.cid))
            client.message('^3You ^7are moved to the game')
            return
>

It worked like a charm until I updated b3 bot few months ago from older 1.10 to newer (dont know exactly when).
Tried even now with the latest 1.10 version and is still same, client.team always returns "-1" in other gametypes like tdm, ts is same. I put on server few bots and their team values were "2" or "-1" aftter team/players swap values stayed same as before. Tested with plugins: admin, status, welcome, with/without poweradminurt (swap command in poweradminurt works prety random too). Logs doesnt show anything intresting.

Maybe I missed something or something did change.

**Comment by danielepantaleone** [comment]
Could you please follow these steps:

- install the latest 1.10dev version
- reboot B3 (set log level down to 8)
- when reboot ia completed, change map
- perform some change teams operations (from spec to game and viceversa)
- post your B3 log

Inviato da iPhone

**Comment by Yascor** [comment]
Hey,
https://gist.github.com/Yascor/e80bdbbf15a6bb0c118f#file-b3-log

**Comment by danielepantaleone** [comment]
Hi again. I added some more verbose logging, so it should be clear now in the log if the team info is getting correctly parsed. Could you give a try again using [this version](https://github.com/BigBrotherBot/big-brother-bot/archive/release-1.10.zip)? Also note that B3 1.10 behaves a bit differently from 1.9.x: events gets enqueued if and only if there are plugins that subscribed for such events: in your setup there is no plugin listening for EVT_CLIENT_TEAM_CHANGE which is the reason why you can't see anything in the log. Could you by chance enable some plugin which listen for such events, like the Poweradminurt?

**Comment by danielepantaleone** [comment]
I tried myself and it seems that there are some issues with the `ClientUserinfoChanged` log line parsing, and so the event is not being fired correctly. The `parseUserinfo`method inherited from `Iourt41Parser`it's not doing its job correctly. Sadly I'm quite busy this week so I do not have time to look into it. Maybe @thomasleveil can help with the matter :smiley:

**Comment by Yascor** [comment]
K, I tried with team game types and poweradminurt and its prety random but weird that after map_restart !swap command cant even find any players corectly or just got incorrect teams BUT with g_gametype 9 (jump mode) it always returns client.team = -1, here log if it can help with something: 
https://gist.github.com/Yascor/322c49f5c18346e63755#file-b3-log

I added line like this in "b3/plugins/poweradminurt/iourt42.py"
>        self.verbose("%s team: %s - %s team: %s" % (client1.name, client1.team, client2.name, client2.team))

when using !swap between player in game and player in spec it returns:
>VERBOSE	'Poweradminurt42Plugin: MY team: -1 - CLONE team: -1'

everything is log :)

**Comment by danielepantaleone** [comment]
Yes, as I said currently B3 is not handling teams correctly. The problem is probably affecting also UrT4.1 parser. A deeper look is needed. I'll try to find some time later in the week, if Thomas doesn't manage to fix the issue.

**Comment by Yascor** [comment]
Ye got it :) Just wanted provide log for him, thank you and hope it will be fixed ;)

**Comment by danielepantaleone** [comment]
Problem should have been fixed here: https://github.com/BigBrotherBot/big-brother-bot/commit/0ac84f234496de6472ae23e0483c44de08b7c963
Could you give it a try by downloading the latest release from [release-1.10](https://github.com/BigBrotherBot/big-brother-bot/archive/release-1.10.zip) branch?

**Comment by Yascor** [comment]
Hey, thank you @danielepantaleone, everything seems working great now :) good job!
