### ISSUE TITLE
[MAKEROOM] retain free duration config value loading is weird

### ISSUE THREAD

**Issue by danielepantaleone** [BigBrotherBot/big-brother-bot#344]
I noticed that while loading the `reatain_free_duration` value from the configuration file, the plugin make some "assumptions" which are not correct:

```python
if self._retain_free_duration >= 30:
    self.warning("global_settings/retain_free_duration must be higher than 30s")
    self._retain_free_duration = 30
```

The if clause and the warning message are opposite, if I'm not mistaken. @thomasleveil could you have a look since I don't know what this setting is supposed to do/be?

https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/plugins/makeroom/__init__.py#L90

**Comment by thomasleveil** [comment]
see https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/conf/plugin_makeroom.ini#L20 for the explanation

**Comment by danielepantaleone** [comment]
Alright, so it was the error message being wrong and not the value. :+1:
