### ISSUE TITLE
HttpytailPlugin: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by tccr** [BigBrotherBot/big-brother-bot#350]
If you specify a remote config via http and set a port, it won't work and spam the log with this message:

*HttpytailPlugin: cannot concatenate 'str' and 'int' objects*

I think the problem is in [line 200 of httpytail](https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/plugins/httpytail/__init__.py#L200), because in [b3.functions](https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/functions.py#L146) the port is defined as int.
I suggest adding str() like this:
```str(self.httpconfig['port']) + '/' + self.httpconfig['path']```
That works for me.

Bug is also in [main](https://github.com/BigBrotherBot/big-brother-bot/blob/master/b3/plugins/httpytail.py#L139), but didn't look closer there. Just remembered that it happened with stable release too.

**Comment by danielepantaleone** [comment]
Thanks for reporting this. The fix will be available in the next daily build.
