### ISSUE TITLE
Adding xml and starting re-open gui?

### ISSUE THREAD

**Issue by cjmwid** [BigBrotherBot/big-brother-bot#351]
Not 100% sure on how to explain this problem im having, tried it with latest 1.10.7dev,1.10.6 & 1.10.5 Some problem with all.

1. Downloaded b3-1.10.7.dev437-20150817-nt32.zip
2. Extracted to folder
3. Copied B3.XML from 1.9.2 ( drag & dropped xml )
4. Added it and clicked the start button, It relaunches the GUI(b3.exe)

Its like its calling B3.exe and not B3_run.exe

If you need anymore information let me know.

**Comment by danielepantaleone** [comment]
Thanks for reporting this issue. I'll try to provide a fix later in the afternoon. 

Inviato da iPhone

**Comment by cjmwid** [comment]
Yep, no problem.  Take your time.  And thanks for the fast reply.
