### ISSUE TITLE
Show config/log button not working

### ISSUE THREAD

**Issue by cjmwid** [BigBrotherBot/big-brother-bot#354]
When i click the Show B3 log and Show B3 config they dont do anything? No errors or prompts just dosnt work.

Could it be because its not ran as an administartor? or not in XML format?

**Comment by danielepantaleone** [comment]
Could you please check the B3 home directory (`.b3 in your user folder`). There should be a log fike in there which is being generated by the GUI application. Post it here so we can see what's going on.

**Comment by cjmwid** [comment]
i have a log and db file.

Heres the log 
150922 16:45:24	INFO    	u'attempt to start b3 process: b3_run.exe --config D:\\b32.xml --console'
150922 16:45:24	DEBUG   	u'updated process in the database: @7:D:\\b32.xml'
150922 16:45:24	INFO    	'process b3 started successfully'
150922 16:45:25	INFO    	u'attempt to start b3 process: b3_run.exe --config D:\\b31.xml --console'
150922 16:45:25	DEBUG   	u'updated process in the database: @8:D:\\b31.xml'
150922 16:45:25	INFO    	'process b3 started successfully'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     150922 16:48:24	INFO    	'shutting down b3 process'
150922 16:48:24	ERROR   	'process b3 errored (1)'
150922 16:48:24	INFO    	'process b3 terminated (62097)'
150922 16:48:27	INFO    	u'attempt to start b3 process: b3_run.exe --config D:\\b32.xml --console'
150922 16:48:27	DEBUG   	u'updated process in the database: @7:D:\\b32.xml'
150922 16:48:27	INFO    	'process b3 started successfully'
150922 16:48:53	INFO    	'shutting down b3 process'
150922 16:48:53	ERROR   	'process b3 errored (1)'
150922 16:48:53	INFO    	'process b3 terminated (62097)'
150922 16:48:56	INFO    	u'attempt to start b3 process: b3_run.exe --config D:\\b32.xml --console'
150922 16:48:56	DEBUG   	u'updated process in the database: @7:D:\\b32.xml'
150922 16:48:56	INFO    	'process b3 started successfully'

**Comment by danielepantaleone** [comment]
The reload config works in the sense that it parses the configuration file again to extract the bot name. Altough you need to stop the B3 instance and reboot after the reload. 

Could you also post the b3.xml (mask passwords)

**Comment by cjmwid** [comment]
<?xml version='1.0' encoding='UTF-8'?>
<configuration>
	<settings name="b3">
		<set name="parser">cod4</set>
		<set name="database">mysql://XXXXXXXX@localhost/b3</set>
		
		<set name="bot_name">Server 1</set>
		
		<set name="bot_prefix">^0(^2b3^0)^7:</set>
		<set name="time_format">%I:%M%p %Z %m/%d/%y</set>
		
		<set name="time_zone">CST</set>
		
		<set name="log_level">9</set>
		
		<set name="logfile">D:\B3 logs\s1.log</set>
	</settings>
	<settings name="server">
		
		<set name="rcon_password">XXXXXXXXXXXXXXXXXXXX</set>
		
		<set name="port">28930</set>
		
		<set name="game_log">D:\Server 7(eu1)\main\games_mp.log</set>
		
		<set name="public_ip">188.165.197.193</set>
		
		<set name="rcon_ip">188.165.197.193</set>
		
		<set name="delay">0.33</set>
		
		<set name="lines_per_second">50</set>
		
		<set name="punkbuster">off</set>
	</settings>
	<settings name="update">
		<set name="channel">stable</set>
	</settings>
	<settings name="autodoc">
		<set name="type">htmltable</set>
		
		<set name="maxlevel">100</set>
		
		<set name="destination">b3_doc.html</set>
	</settings>
	<settings name="messages">
		<set name="kicked_by">$clientname^7 was kicked by $adminname^7 $reason</set>
		<set name="kicked">$clientname^7 was kicked $reason</set>
		<set name="banned_by">$clientname^7 was banned by $adminname^7 $reason</set>
		<set name="banned">$clientname^7 was banned $reason</set>
		<set name="temp_banned_by">$clientname^7 was temp banned by $adminname^7 for $banduration^7 $reason</set>
		<set name="temp_banned">$clientname^7 was temp banned for $banduration^7 $reason</set>
		<set name="unbanned_by">$clientname^7 was un-banned by $adminname^7 $reason</set>
		<set name="unbanned">$clientname^7 was un-banned $reason</set>
	</settings>
	<settings name="plugins">
		<set name="external_dir">D:/B3 Server 7(eu1)/extplugins</set>
	</settings>
	<plugins>
		
		<plugin config="D:/B3 Server 7(eu1)/conf/plugin_spamcontrol.xml" name="spamcontrol" />
		<plugin config="D:/B3 Server 7(eu1)/conf/plugin_admin.xml" name="admin" />
		<plugin config="D:/B3 Server 7(eu1)/conf/plugin_stats.xml" name="stats" />
		<plugin config="D:/B3 Server 7(eu1)/conf/plugin_pingwatch.xml" name="pingwatch" />
		<plugin config="D:/B3 Server 7(eu1)/conf/plugin_adv.xml" name="adv" />
		<plugin config="D:/B3 Server 7(eu1)/conf/plugin_status.xml" name="status" />
		<plugin config="D:/B3 Server 7(eu1)/conf/plugin_welcome.xml" name="welcome" />
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/plugin_chatlogger.xml" name="chatlogger" />
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/xlrstats.xml" name="xlrstats" />
		<plugin name="servermonitor" config="D:/B3 Server 7(eu1)/conf/plugin_servermonitor.cfg" />
		<plugin config="D:/B3 Server 7(eu1)/conf/superadmin.xml" name="superadmin" />
        <plugin name="banlist" config="D:/B3 Server 7(eu1)/conf/plugin_banlist.xml"/>
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/website.xml" name="website" />
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/openbanter.xml" name="openbanter" />
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/aimbotdetector.xml" name="aimbotdetector" />
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/asciikick.xml" name="asciikick" />		
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/namechangers.xml" name="namechangers" />
		<plugin name="tagprotect" config="D:/B3 Server 7(eu1)/extplugins/conf/tagprotect.xml"/>
		<plugin name="calladmin" config="D:/B3 Server 7(eu1)/extplugins/conf/plugin_calladmin.ini"/>
		<plugin config="D:/B3 Server 7(eu1)/extplugins/conf/hackban.xml" name="hackban" />
	</plugins>
</configuration>

**Comment by danielepantaleone** [comment]
This is just weird. It should work properly. I'll try to reproduce this on my system but it's going to take sometime since I'm pretty busy.

**Comment by cjmwid** [comment]
Thats fine if it helps its on Windows Server 2012 r2 :)

If you need more system spec's just ask id be happy to provide
