### ISSUE TITLE
playerstats kills & deaths inaccurate, map stats accurate

### ISSUE THREAD

**Issue by that0n3guy** [BigBrotherBot/big-brother-bot#356]
On the release-1.10 branch.  I have an issue where the player stats are inaccurate but my map stats are right... not sure why.

Out of 6 users played on the new test server only 2's kills & deaths are right.

I don't see anything funky in the b3 logs.

**Comment by danielepantaleone** [comment]
Hi, for this type of support it's better to use our [Forum](http://forum.bigbrotherbot.net/). We use GitHub issues only for code related problems. Also you would need to be more specific or provide a B3 log showing the problem otherwise we won't be able to help you.

**Comment by that0n3guy** [comment]
Just in case anyone comes here in the future: 
http://forum.bigbrotherbot.net/xlr-releases/playerstats-kills-deaths-inaccurate-but-map-stats-are-accurate/
