### ISSUE TITLE
b3 does not respond to commands

### ISSUE THREAD

**Issue by veganexe** [BigBrotherBot/big-brother-bot#378]
## CentOS 7.3

CoD4 server and b3 runs. B3 even displays the start-up message in-game. But none of the commands work.

Here are the log files of both b3 and cod4,

[games_mp.log](https://github.com/BigBrotherBot/big-brother-bot/files/1347285/games_mp.log)

[b3.log](https://github.com/BigBrotherBot/big-brother-bot/files/1347286/b3.log)

**Comment by danielepantaleone** [comment]
Please use the forum for this kind of problems: http://forum.bigbrotherbot.net/
