### ISSUE TITLE
[XLRSTATS][COD4X] 1054, "Unknown column 'None' in 'where clause'"

### ISSUE THREAD

**Issue by 3aTeuHuk** [BigBrotherBot/big-brother-bot#410]
Hey. When I try to turn on b3 with xlrstats I get this error:
> 191115 09:50:22 ERROR    'Query failed [SELECT MAX(xlr_playerstats.skill) AS max_skill, MIN(xlr_playerstats.skill) AS min_skill, SUM(xlr_playerstats.skill) AS sum_skill,\n               AVG(xlr_playerstats.skill) AS avg_skill , COUNT(xlr_playerstats.id) AS cnt\n               FROM xlr_playerstats, clients\n               WHERE clients.id = xlr_playerstats.client_id\n               AND xlr_playerstats.client_id <> None\n               AND (xlr_playerstats.kills + xlr_playerstats.deaths) > 50\n               AND 1573829422 - clients.time_edit <= 5184000] None: (1054, "Unknown column \'None\' in \'where clause\'")'
191115 09:50:22 ERROR    'Could not start plugin xlrstats'
Traceback (most recent call last):
  File "/home/servers/big-brother-bot/b3/parser.py", line 948, in startPlugins
    start_plugin(self, plugin_name)
  File "/home/servers/big-brother-bot/b3/parser.py", line 939, in start_plugin
    p.onStartup()
  File "/home/servers/big-brother-bot/b3/plugins/xlrstats/__init__.py", line 257, in onStartup
    self.correctStats()
  File "/home/servers/big-brother-bot/b3/plugins/xlrstats/__init__.py", line 1558, in correctStats
    cursor = self.query(q)
  File "/home/servers/big-brother-bot/b3/storage/common.py", line 635, in query
    raise e
OperationalError: (1054, "Unknown column 'None' in 'where clause'")

**Comment by ayushishara** [comment]
how to fix this ?

**Comment by derrexal** [comment]
> how to fix this ?

Обратите внимание на слово 'None' в запросе. Это слово необходимо обернуть в одинарные кавычки(''). Таким образом полный запрос будет выглядеть так:(Место, которое требовало редактирования выделено жирным шрифтом)

SELECT MAX(xlr_playerstats.skill) AS max_skill, MIN(xlr_playerstats.skill) AS min_skill, SUM(xlr_playerstats.skill) AS sum_skill,\n AVG(xlr_playerstats.skill) AS avg_skill , COUNT(xlr_playerstats.id) AS cnt\n FROM xlr_playerstats, clients\n WHERE clients.id = xlr_playerstats.client_id\n AND xlr_playerstats.client_id <> **'None'**\n AND (xlr_playerstats.kills + xlr_playerstats.deaths) > 50\n AND 1573829422 - clients.time_edit <= 5184000
