### ISSUE TITLE
DB connecting failed

### ISSUE THREAD

**Issue by thrk1993** [BigBrotherBot/big-brother-bot#419]
b3.log

201223 06:51:59 BOT      'Connecting to MySQL database: mysql://[user name correct]:******@127.0.0.1:3306/[db name correct]'
201223 06:51:59 ERROR    'Database connection failed: working in remote mode: 255 - [(\'/home/rider/b3/big-brother-bot-master/b3/storage/mysql.py\', 287, \'connect\', \'charset="utf8")\'), (\'/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py\', 88, \'Connect\', \'return Connection(*args, **kwargs)\'), (\'/usr/local/lib/python2.7/dist-packages/pymysql/connections.py\', 644, \'__init__\', \'self._connect()\'), (\'/usr/local/lib/python2.7/dist-packages/pymysql/connections.py\', 837, \'_connect\', \'self._get_server_information()\'), (\'/usr/local/lib/python2.7/dist-packages/pymysql/connections.py\', 1072, \'_get_server_information\', \'self.server_charset = charset_by_id(lang).name\'), (\'/usr/local/lib/python2.7/dist-packages/pymysql/charset.py\', 34, \'by_id\', \'return self._by_id[id]\')]'
201223 06:51:59 BOT      'Game log is: /home/rider/serverfiles/main/games_mp.log'

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

b3.xml

<set name="database">mysql://[user name correct]:[password correct]@127.0.0.1/[db name correct]</set>

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Database table structure

Database changed
mysql> show tables;
+---------------------+
| Tables_in_[db name] |
+---------------------+
| aliases             |
| clients             |
| cmdgrants           |
| ctime               |
| current_clients     |
| current_svars       |
| data                |
| groups              |
| ipaliases           |
| penalties           |
| xlr_actionstats     |
| xlr_bodyparts       |
| xlr_history_monthly |
| xlr_history_weekly  |
| xlr_mapstats        |
| xlr_opponents       |
| xlr_playeractions   |
| xlr_playerbody      |
| xlr_playermaps      |
| xlr_playerstats     |
| xlr_weaponstats     |
| xlr_weaponusage     |
+---------------------+

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Database name, MySQL username, password everything correct. perticuler database already created. b3 table structure have. but, 

Starting B3      : www.bigbrotherbot.net (b3) v1.12 [^IronPigeon]
Autorestart mode : OFF
Checking update  : timed out
Loading config   : @conf/b3.xml
Loading parser   : cod4x18
Activating log   : ~/b3/big-brother-bot-master/b3.log
Connecting to DB : FAILED!
Using gamelog    : ~/serverfiles/main/games_mp.log
Testing RCON     : OK
Loading events   : 42 events loaded
Loading plugins  : .................... (20)

Database connecting failed. if anyone can help me place help .....

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by 82ndab-Bravo17** [comment]
1. Make certain that Mysql is running - try to connect from a browser by putting in the url
2. Check the user permissions fro the b3 database
3. Try a simple password like with letters only
4. Try with the root user and password

**Comment by thrk1993** [comment]
> 1. Make certain that Mysql is running - try to connect from a browser by putting in the url
> 2. Check the user permissions fro the b3 database
> 3. Try a simple password like with letters only
> 4. Try with the root user and password

**Comment by thrk1993** [comment]
> 1. Make certain that Mysql is running - try to connect from a browser by putting in the url
> 2. Check the user permissions fro the b3 database
> 3. Try a simple password like with letters only
> 4. Try with the root user and password

@82ndab-Bravo17  Tried no answer... the same result.

**Comment by 82ndab-Bravo17** [comment]
What happened with "try to connect from a browser by putting in the url"

**Comment by thrk1993** [comment]
@82ndab-Bravo17  I have done that, it work with phpmyadmin. i can access with username and password

**Comment by 82ndab-Bravo17** [comment]
Maybe Firewall issue?

**Comment by thrk1993** [comment]
@82ndab-Bravo17 firewall.....??? hmmm..... what about MySQL connector?...

**Comment by 82ndab-Bravo17** [comment]
Put this in the address box of your browser, replacing the missing bits with your correct info, including password

mysql://[user name correct]:******@127.0.0.1:3306/[db name correct]'

**Comment by thrk1993** [comment]
> Put this in the address box of your browser, replacing the missing bits with your correct info, including password
> 
> mysql://[user name correct]:******@127.0.0.1:3306/[db name correct]'

Sorry, @82ndab-Bravo17 I'm using SSH (putty) to access the server. so I don't know how to get a browser to paste the above address. I can access PHPMyAdmin using PuTTY Tunnels. That's can be. I'm using a Windows machine.

**Comment by 82ndab-Bravo17** [comment]
How are you running B3?

**Comment by thrk1993** [comment]
@82ndab-Bravo17 using "python b3_run.py" command, in SSH (putty)

**Comment by 82ndab-Bravo17** [comment]
You can't use Remote Desktop to access the machine?

**Comment by thrk1993** [comment]
I'm not the owner @82ndab-Bravo17 because I'm logging in using putty & WinSCP.

**Comment by 82ndab-Bravo17** [comment]
Perhaps your access doesn't give you the needed permissions?  I'm afraid that its impossible to help if even you don't have enough access to troubleshoot properly.

**Comment by thrk1993** [comment]
yaa... @82ndab-Bravo17 I can understand. I'll try to take the owner to reply here... he's busy. Thanks for your continuous replying.

**Comment by thrk1993** [comment]
@82ndab-Bravo17 
I have fixed the database connecting issue. now another error occurs do you have any idea about this? 

210403 18:37:24 BOT      'www.bigbrotherbot.net (b3) v1.12 [^IronPigeon]'
210403 18:37:24 BOT      'Python: 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 9.2.1 20191008]'
210403 18:37:24 BOT      'Default encoding: ascii'
210403 18:37:24 BOT      'Starting Cod4X18Parser v0.2 for server (sensitive data deleted) (autorestart = OFF)'
210403 18:37:24 BOT      '--------------------------------------------'
210403 18:37:24 BOT      'Connecting to MySQL database: (sensitive data deleted)
210403 18:37:24 BOT      'Successfully established a connection with MySQL database'
210403 18:37:24 BOT      'Game log is: /home/rider/serverfiles/main/games_mp.log'
210403 18:37:24 BOT      u'Starting bot reading file: /home/rider/serverfiles/main/games_mp.log'
210403 18:37:24 BOT      'Rcon status cache expire time: [2 sec] Type: [False]'
210403 18:37:24 BOT      'Game name is: cod4'
210403 18:37:24 VERBOSE  "RCON sending (sensitive data deleted) 'status'"
210403 18:37:25 BOT      u'Loading plugins (external plugin directory: /home/rider/b3/New folder/big-brother-bot-master/b3/extplugins)'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_admin.ini for plugin admin'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_adv.xml for plugin adv'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_cmdmanager.ini for plugin cmdmanager'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_pingwatch.ini for plugin pingwatch'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_pluginmanager.ini for plugin pluginmanager'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_punkbuster.ini for plugin punkbuster'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_spamcontrol.ini for plugin spamcontrol'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_stats.ini for plugin stats'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_status.ini for plugin status'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_tk.ini for plugin tk'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_welcome.ini for plugin welcome'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_customcommands.ini for plugin customcommands'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_location.ini for plugin location'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_firstkill.ini for plugin firstkill'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_geowelcome.ini for plugin geowelcome'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_spree.ini for plugin spree'
210403 18:37:25 BOT      u'Loading configuration file /home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_xlrstats.ini for plugin xlrstats'
210403 18:37:25 DEBUG    'No configuration file specified for plugin duel: is not required either'
210403 18:37:25 VERBOSE  'Discordban is not a built-in plugin (No module named discordban)'
210403 18:37:25 VERBOSE  u'Trying external plugin directory : /home/rider/b3/New folder/big-brother-bot-master/b3/extplugins'
210403 18:37:25 ERROR    'Could not load plugin discordban'
Traceback (most recent call last):
  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 702, in loadPlugins
    mod = self.pluginImport(p['name'], p['path'])
  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 919, in pluginImport
    fp, pathname, description = imp.find_module(name, [self.config.get_external_plugins_dir()])
ImportError: No module named discordban
210403 18:37:25 VERBOSE  'Masteradmin is not a built-in plugin (No module named masteradmin)'
210403 18:37:25 VERBOSE  u'Trying external plugin directory : /home/rider/b3/New folder/big-brother-bot-master/b3/extplugins'
210403 18:37:25 ERROR    'Could not load plugin masteradmin'
Traceback (most recent call last):
  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 702, in loadPlugins
    mod = self.pluginImport(p['name'], p['path'])
  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 919, in pluginImport
    fp, pathname, description = imp.find_module(name, [self.config.get_external_plugins_dir()])
ImportError: No module named masteradmin
210403 18:37:25 DEBUG    'Plugin location has unmet dependency : geolocation : trying to load plugin geolocation...'
210403 18:37:25 DEBUG    'Looking for plugin geolocation module and configuration file...'
210403 18:37:25 DEBUG    'No configuration file specified for plugin geolocation: is not required either'
210403 18:37:25 DEBUG    'Plugin location dependency satisfied: geolocation'
210403 18:37:25 BOT      'Sorting plugins according to their dependency tree...'
210403 18:37:25 BOT      'Ready to create plugin instances: admin, adv, cmdmanager, pingwatch, pluginmanager, punkbuster, spamcontrol, stats, status, tk, welcome, customcommands, geolocation, firstkill, geowelcome, spree, xlrstats, duel, location'
210403 18:37:25 BOT      u'Loading plugin #1 : admin [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_admin.ini]'
210403 18:37:25 DEBUG    'AdminPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'AdminPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'AdminPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'AdminPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin admin (1.35 - ThorN, xlr8or, Courgette, Ozon, Fenix) loaded'
210403 18:37:25 BOT      u'Loading plugin #2 : adv [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_adv.xml]'
210403 18:37:25 DEBUG    'AdvPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'AdvPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'AdvPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'AdvPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin adv (1.6.1 - ThorN) loaded'
210403 18:37:25 BOT      u'Loading plugin #3 : cmdmanager [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_cmdmanager.ini]'
210403 18:37:25 DEBUG    'CmdmanagerPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'CmdmanagerPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'CmdmanagerPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'CmdmanagerPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin cmdmanager (1.4 - Fenix) loaded'
210403 18:37:25 BOT      u'Loading plugin #4 : pingwatch [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_pingwatch.ini]'
210403 18:37:25 DEBUG    'PingwatchPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'PingwatchPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'PingwatchPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'PingwatchPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin pingwatch (1.4 - ThorN) loaded'
210403 18:37:25 BOT      u'Loading plugin #5 : pluginmanager [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_pluginmanager.ini]'
210403 18:37:25 DEBUG    'PluginmanagerPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'PluginmanagerPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'PluginmanagerPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'PluginmanagerPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin pluginmanager (1.2 - Fenix) loaded'
210403 18:37:25 BOT      u'Loading plugin #6 : punkbuster [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_punkbuster.ini]'
210403 18:37:25 DEBUG    'PunkbusterPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'PunkbusterPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'PunkbusterPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'PunkbusterPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin punkbuster (1.3 - ThorN) loaded'
210403 18:37:25 BOT      u'Loading plugin #7 : spamcontrol [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_spamcontrol.ini]'
210403 18:37:25 DEBUG    'SpamcontrolPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'SpamcontrolPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'SpamcontrolPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'SpamcontrolPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin spamcontrol (1.4.4 - ThorN, Courgette) loaded'
210403 18:37:25 BOT      u'Loading plugin #8 : stats [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_stats.ini]'
210403 18:37:25 DEBUG    'StatsPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'StatsPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'StatsPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'StatsPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin stats (1.5.1 - ThorN, GrosBedo) loaded'
210403 18:37:25 BOT      u'Loading plugin #9 : status [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_status.ini]'
210403 18:37:25 DEBUG    'StatusPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'StatusPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'StatusPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'StatusPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin status (1.6.5 - ThorN) loaded'
210403 18:37:25 BOT      u'Loading plugin #10 : tk [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_tk.ini]'
210403 18:37:25 DEBUG    'TkPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'TkPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'TkPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'TkPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin tk (1.5 - ThorN, mindriot, Courgette, xlr8or, SGT, 82ndab-Bravo17, ozon, Fenix) loaded'
210403 18:37:25 BOT      u'Loading plugin #11 : welcome [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_welcome.ini]'
210403 18:37:25 DEBUG    'WelcomePlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'WelcomePlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'WelcomePlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'WelcomePlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin welcome (1.4 - ThorN, xlr8or, Courgette) loaded'
210403 18:37:25 BOT      u'Loading plugin #12 : customcommands [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_customcommands.ini]'
210403 18:37:25 DEBUG    'CustomcommandsPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'CustomcommandsPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'CustomcommandsPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'CustomcommandsPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin customcommands (1.2 - Courgette) loaded'
210403 18:37:25 BOT      'Loading plugin #13 : geolocation [--]'
210403 18:37:25 DEBUG    'GeolocationPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'GeolocationPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'GeolocationPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'GeolocationPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 INFO     'GeolocationPlugin: creating geolocators object instances...'
210403 18:37:25 BOT      'Plugin geolocation (1.5 - Fenix) loaded'
210403 18:37:25 BOT      u'Loading plugin #14 : firstkill [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_firstkill.ini]'
210403 18:37:25 DEBUG    'FirstkillPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'FirstkillPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'FirstkillPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'FirstkillPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin firstkill (1.5.2 - PtitBigorneau - www.ptitbigorneau.fr) loaded'
210403 18:37:25 BOT      u'Loading plugin #15 : geowelcome [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_geowelcome.ini]'
210403 18:37:25 DEBUG    'GeowelcomePlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'GeowelcomePlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'GeowelcomePlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'GeowelcomePlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin geowelcome (1.3.1 - SGT) loaded'
210403 18:37:25 BOT      u'Loading plugin #16 : spree [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_spree.ini]'
210403 18:37:25 DEBUG    'SpreePlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'SpreePlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'SpreePlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'SpreePlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin spree (1.2.3 - Walker, ThorN) loaded'
210403 18:37:25 BOT      u'Loading plugin #17 : xlrstats [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_xlrstats.ini]'
210403 18:37:25 DEBUG    'XlrstatsPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'XlrstatsPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'XlrstatsPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'XlrstatsPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin xlrstats (3.0.0-beta.17 - xlr8or & ttlogic) loaded'
210403 18:37:25 BOT      'Loading plugin #18 : duel [--]'
210403 18:37:25 DEBUG    'DuelPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'DuelPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'DuelPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'DuelPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin duel (1.2 - Courgette) loaded'
210403 18:37:25 BOT      u'Loading plugin #19 : location [/home/rider/b3/New folder/big-brother-bot-master/b3/conf/plugin_location.ini]'
210403 18:37:25 DEBUG    'LocationPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'LocationPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'LocationPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'LocationPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin location (2.3 - Fenix, Courgette) loaded'
210403 18:37:25 BOT      'Loading plugin : publist'
210403 18:37:25 DEBUG    'PublistPlugin: register event <Stop Process>'
210403 18:37:25 DEBUG    'PublistPlugin: created event mapping: <Stop Process:onStop>'
210403 18:37:25 DEBUG    'PublistPlugin: register event <Program Exit>'
210403 18:37:25 DEBUG    'PublistPlugin: created event mapping: <Program Exit:onExit>'
210403 18:37:25 BOT      'Plugin publist (1.14 - ThorN, Courgette) loaded'
210403 18:37:25 DEBUG    'Creating the event queue with size 50'
210403 18:37:25 BOT      'Starting parser..'
210403 18:37:25 VERBOSE  "RCON sending (45.32.113.186:28960) 'sv_usesteam64id  1'"
210403 18:37:26 VERBOSE  "RCON sending (45.32.113.186:28960) 'plugininfo b3hide'"
210403 18:37:27 VERBOSE  "RCON sending (45.32.113.186:28960) 'say ^0(^2b3^0)^7: ^8www.bigbrotherbot.net ^0(^8b3^0) ^9v1.12'"
210403 18:37:27 INFO     'AdminPlugin: ------ loading warn_reasons from config file ------'
210403 18:37:27 INFO     "AdminPlugin: warn reason 'default': (60.0, '^7behave yourself')"
210403 18:37:27 INFO     "AdminPlugin: warn reason 'generic': (60.0, '^7')"
210403 18:37:27 INFO     'AdminPlugin: rule9      3 hours   \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
210403 18:37:27 INFO     'AdminPlugin: rule8      3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
210403 18:37:27 INFO     'AdminPlugin: rule3      1 day     \t"^3Rule #3: No arguing with admins (listen and learn or leave)" '
210403 18:37:27 INFO     'AdminPlugin: rule2      1 day     \t"^3Rule #2: No clan stacking, members must split evenly between the teams" '
210403 18:37:27 INFO     'AdminPlugin: rule1      1.4 week  \t"^3Rule #1: No racism of any kind" '
210403 18:37:27 INFO     'AdminPlugin: rule7      1 day     \t"^3Rule #7: No advertising or spamming of websites or servers" '
210403 18:37:27 INFO     'AdminPlugin: rule6      1 day     \t"^3Rule #6: No recruiting for your clan, your server, or anything else" '
210403 18:37:27 INFO     'AdminPlugin: rule5      1 hour    \t"^3Rule #5: No offensive or potentially offensive names, annoying names, or in-game (double caret (^)) color in names" '
210403 18:37:27 INFO     'AdminPlugin: rule4      1 day     \t"^3Rule #4: No abusive language or behavior towards admins or other players" '
210403 18:37:27 INFO     'AdminPlugin: adv        1 day     \t"^3Rule #7: No advertising or spamming of websites or servers" '
210403 18:37:27 INFO     'AdminPlugin: afk        5 minutes \t"^7you appear to be away from your keyboard" '
210403 18:37:27 INFO     'AdminPlugin: generic    1 hour    \t"^7" '
210403 18:37:27 INFO     'AdminPlugin: ci         5 minutes \t"^7connection interupted, reconnect" '
210403 18:37:27 INFO     'AdminPlugin: racism     1.4 week  \t"^3Rule #1: No racism of any kind" '
210403 18:37:27 INFO     'AdminPlugin: color      1 hour    \t"^7No in-game (double caret (^)) color in names" '
210403 18:37:27 INFO     'AdminPlugin: fakecmd    1 hour    \t"^7do not use fake commands" '
210403 18:37:27 INFO     'AdminPlugin: tk         1 day     \t"^7stop team killing!" '
210403 18:37:27 INFO     'AdminPlugin: nocmd      1 hour    \t"^7do not use commands that you do not have access to, try using !help" '
210403 18:37:27 INFO     'AdminPlugin: spec       5 minutes \t"^7spectator too long on full server" '
210403 18:37:27 INFO     'AdminPlugin: spawnfire  3 hours   \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
210403 18:37:27 INFO     'AdminPlugin: cuss       3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
210403 18:37:27 INFO     'AdminPlugin: jerk       1 day     \t"^3Rule #4: No abusive language or behavior towards admins or other players" '
210403 18:37:27 INFO     'AdminPlugin: sfire      3 hours   \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
210403 18:37:27 INFO     'AdminPlugin: spam       1 hour    \t"^7do not spam, shut-up!" '
210403 18:37:27 INFO     'AdminPlugin: rule10     3 days    \t"^3Rule #10: Offense players must play for the objective and support their team" '
210403 18:37:27 INFO     'AdminPlugin: stack      1 day     \t"^3Rule #2: No clan stacking, members must split evenly between the teams" '
210403 18:37:27 INFO     'AdminPlugin: lang       3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
210403 18:37:27 INFO     'AdminPlugin: obj        1 hour    \t"^7go for the objective!" '
210403 18:37:27 INFO     'AdminPlugin: name       1 hour    \t"^3Rule #5: No offensive or potentially offensive names, annoying names, or in-game (double caret (^)) color in names" '
210403 18:37:27 INFO     'AdminPlugin: language   3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
210403 18:37:27 INFO     'AdminPlugin: default    1 hour    \t"^7behave yourself" '
210403 18:37:27 INFO     'AdminPlugin: profanity  3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
210403 18:37:27 INFO     'AdminPlugin: camp       1 hour    \t"^7stop camping or you will be kicked!" '
210403 18:37:27 INFO     'AdminPlugin: recruit    1 day     \t"^3Rule #6: No recruiting for your clan, your server, or anything else" '
210403 18:37:27 INFO     'AdminPlugin: badname    1 hour    \t"^7No offensive, potentially offensive, or annoying names" '
210403 18:37:27 INFO     'AdminPlugin: spectator  5 minutes \t"^7spectator too long on full server" '
210403 18:37:27 INFO     'AdminPlugin: argue      1 day     \t"^3Rule #3: No arguing with admins (listen and learn or leave)" '
210403 18:37:27 INFO     'AdminPlugin: -------------- warn_reasons loaded ----------------'
210403 18:37:27 DEBUG    'AdminPlugin: loaded warn/warn_delay: 15'
210403 18:37:27 DEBUG    'AdminPlugin: loaded warn/instant_kick_num: 5'
210403 18:37:27 DEBUG    'AdminPlugin: loaded warn/alert_kick_num: 3'
210403 18:37:27 DEBUG    'AdminPlugin: loaded warn/warn_command_abusers: False'
210403 18:37:27 INFO     'STDOUT "ERROR: \'MySQLConnection\' object has no attribute \'open\'"'
210403 18:37:27 INFO     "STDOUT '\\n'"
210403 18:37:27 ERROR    "STDERR 'Traceback (most recent call last):\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/__init__.py", line 328, in start\\n\''
210403 18:37:27 ERROR    "STDERR '    console.start()\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 470, in start\\n\''
210403 18:37:27 ERROR    "STDERR '    self.call_plugins_onLoadConfig()\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 841, in call_plugins_onLoadConfig\\n\''
210403 18:37:27 ERROR    "STDERR '    p.onLoadConfig()\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/plugins/admin/__init__.py", line 150, in onLoadConfig\\n\''
210403 18:37:27 ERROR    'STDERR "    self._noreason_level = self.console.getGroupLevel(self.config.get(\'settings\', \'noreason_level\'))\\n"'
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 1067, in getGroupLevel\\n\''
210403 18:37:27 ERROR    "STDERR '    group = self.getGroup(data)\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/decorators.py", line 82, in __call__\\n\''
210403 18:37:27 ERROR    "STDERR '    res = cache[key] = self.func(*args, **kw)\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/parser.py", line 1059, in getGroup\\n\''
210403 18:37:27 ERROR    "STDERR '    return self.storage.getGroup(g)\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/storage/common.py", line 553, in getGroup\\n\''
210403 18:37:27 ERROR    "STDERR '    cursor = self.query(query)\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/storage/common.py", line 625, in query\\n\''
210403 18:37:27 ERROR    "STDERR '    connection = self.getConnection()\\n'"
210403 18:37:27 ERROR    'STDERR \'  File "/home/rider/b3/New folder/big-brother-bot-master/b3/storage/mysqlDB.py", line 58, in getConnection\\n\''
210403 18:37:27 ERROR    "STDERR '    if self.db and self.db.open:\\n'"
210403 18:37:27 ERROR    'STDERR "AttributeError: \'MySQLConnection\' object has no attribute \'open\'\\n"'
210403 18:37:27 BOT      'Shutting down...'
210403 18:37:27 INFO     'StatusPlugin: B3 stop/exit.. updating status'
210403 18:37:27 DEBUG    'StatusPlugin: writing XML status to ~/status.xml'
210403 18:37:27 ERROR    "[Errno 2] No such file or directory: '~/status.xml'"

**Comment by 82ndab-Bravo17** [comment]
Until you get it running remove all plugins from the config other than admin.

How did you solve the DB Connection issue, since the two are possibly related?

**Comment by thrk1993** [comment]
@82ndab-Bravo17 friend, can I contact you by email?  if you can help me, put a mail for me plz... 
uvtharaka@gmail.com

**Comment by 82ndab-Bravo17** [comment]
Please continue here, that way if someone else has the same issue they will be able to see the solution.

**Comment by thrk1993** [comment]
@82ndab-Bravo17 problem solved friend, prob have in PHP version it needs 5.6 we have 7. so we hire another server one friend supports thanks for ur help.
