### ISSUE TITLE
No error but not working

### ISSUE THREAD

**Issue by obteo** [BigBrotherBot/big-brother-bot#421]
Hello, I have no error in logs now but seems B3 can't write on the database... any idea please? @82ndab-Bravo17

**Comment by 82ndab-Bravo17** [comment]
Can't write or doesn't seem to be writing?

Can't write should produce an error I would think?

**Comment by obteo** [comment]
Hi bro! i figured it out... after so many time I forgot the RCON password must be at least 8 chars.... my bad sorry to bother you. :* @82ndab-Bravo17
