### ISSUE TITLE
Connecting to DB : FAILED!

### ISSUE THREAD

**Issue by michelszabo** [BigBrotherBot/big-brother-bot#434]
Sto provando a configurare B3 per MW2 e anche utilizzando una password di base sull'utente b3 e sto riscontrando questo problema.
Qualcuno può aiutarmi? Per favore

**Comment by danielepantaleone** [comment]
Ciao @michelszabo 

Please post the b3 log here so that we can help you.

**Comment by michelszabo** [comment]
Below is the log.
Thanks

> 240619 16:15:50	BOT    	'www.bigbrotherbot.net (b3) v1.9.2 [nt] [PoisonIvy] [Win32 standalone]'
240619 16:15:50	BOT    	'Python: 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]'
240619 16:15:50	BOT    	'Default encoding: ascii'
240619 16:15:50	BOT    	'Starting Cod2Parser v1.3.0 for server 192.168.18.233:28960'
240619 16:15:50	BOT    	'--------------------------------------------'
240619 16:15:50	BOT    	'Attempting to connect to database b3'
240619 16:15:50	ERROR	"Database connection failed, working in remote mode: Unknown database protocol file - [('b3\\\\storage\\\\database.pyo', 243, 'connect', None), ('b3\\\\storage\\\\database.pyo', 206, 'getConnection', None)]"
240619 16:15:50	BOT    	'Game log C:\\MW2 iw4x_full_game\\userraw\\logs\\games_mp.log'
240619 16:15:50	BOT    	'Starting bot reading file C:\\MW2 iw4x_full_game\\userraw\\logs\\games_mp.log'
240619 16:15:50	BOT    	'rcon status Cache Expire Time: [2 sec] Type: [memory]'
240619 16:15:50	VERBOSE	"RCON sending (192.168.18.233:28960) 'status'"
240619 16:15:51	BOT    	'Loading Plugins (external plugin directory: C:\\MW2 iw4x_full_game\\BigBrotherBot-1.9.2-win32\\extplugins)'
240619 16:15:51	BOT    	'Loading Plugin #1 censor [conf\\plugin_censor.xml]'
240619 16:15:51	BOT    	'CensorPlugin: Loading config conf\\plugin_censor.xml for CensorPlugin'
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'shit' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'ass' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'asshole' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'fuck' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'fuc' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'cunt' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'cock' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'dick' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'bitch' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'biatch' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'fag' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'nigger' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'pussy' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'lul' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'flikker' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'homo' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'kanker' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'teringlijer' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'kut' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'hoer' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'neuk' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'vittu' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'paskiainen' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'kusipaeae' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'fitte' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'pikk' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'hore' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'fitta' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'knullare' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'kuksugare' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'huora' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'spica' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'piroca' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'caralho' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'puta' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'cabra' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'maricon' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'pinche' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'batard' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'encule' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'merde' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'putain' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'salaud' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'connard' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'salopard' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'salope' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'scheisse' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'arsch' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'huendin' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'kopulieren' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'fick' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'chuj' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'kutas' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'fiut' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'pedal' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'cipa' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'pizda' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'ciota' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'dupek' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'kurwa' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'skurwysyn' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'zajebac' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'pojebac' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'wyjebac' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'pierdolic' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'rozpierdalac' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'popierdolony' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badword rule 'wypierdalac' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'doublecolor' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'ass' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'fuck' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'shit' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'bitch' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'pussy' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'nigger' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'cunt' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'nazi' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'jihad' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'admin' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'hitler' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'asshole' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'kut' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'hoer' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'huora' loaded"
240619 16:15:51	DEBUG	"CensorPlugin: badname rule 'puta' loaded"
240619 16:15:51	DEBUG	'Register Event: Stop Process: CensorPlugin'
240619 16:15:51	DEBUG	'Register Event: Program Exit: CensorPlugin'
240619 16:15:51	BOT    	'Plugin censor (3.1 - ThorN, xlr8or, Bravo17, Courgette) loaded'
240619 16:15:51	BOT    	'Loading Plugin #2 spamcontrol [conf\\plugin_spamcontrol.xml]'
240619 16:15:51	BOT    	'SpamcontrolPlugin: Loading config conf\\plugin_spamcontrol.xml for SpamcontrolPlugin'
240619 16:15:51	BOT    	'Attempting to connect to database b3'
240619 16:15:51	ERROR	'Error loading plugin spamcontrol'
Traceback (most recent call last):
  File "b3\parser.pyo", line 674, in loadPlugins
  File "b3\plugin.pyo", line 56, in __init__
  File "b3\plugin.pyo", line 115, in loadConfig
  File "b3\plugins\spamcontrol.pyo", line 61, in onLoadConfig
  File "b3\parser.pyo", line 895, in getGroupLevel
  File "b3\decorators.pyo", line 60, in __call__
  File "b3\parser.pyo", line 887, in getGroup
  File "b3\storage\database.pyo", line 858, in getGroup
AttributeError: 'NoneType' object has no attribute 'getOneRow'
240619 16:15:51	BOT    	'Loading Plugin #3 admin [conf\\plugin_admin.xml]'
240619 16:15:51	BOT    	'AdminPlugin: Loading config conf\\plugin_admin.xml for AdminPlugin'
240619 16:15:51	INFO	'AdminPlugin: ------ loading warn_reasons from config file ------'
240619 16:15:51	INFO	"AdminPlugin: warn reason 'default' : (60.0, '^7behave yourself')"
240619 16:15:51	INFO	"AdminPlugin: warn reason 'generic' : (60.0, '^7')"
240619 16:15:51	INFO	'AdminPlugin: rule9      3 hours   \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
240619 16:15:51	INFO	'AdminPlugin: rule8      3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
240619 16:15:51	INFO	'AdminPlugin: rule3      1 day     \t"^3Rule #3: No arguing with admins (listen and learn or leave)" '
240619 16:15:51	INFO	'AdminPlugin: rule2      1 day     \t"^3Rule #2: No clan stacking, members must split evenly between the teams" '
240619 16:15:51	INFO	'AdminPlugin: rule1      1.4 week  \t"^3Rule #1: No racism of any kind" '
240619 16:15:51	INFO	'AdminPlugin: rule7      1 day     \t"^3Rule #7: No advertising or spamming of websites or servers" '
240619 16:15:51	INFO	'AdminPlugin: rule6      1 day     \t"^3Rule #6: No recruiting for your clan, your server, or anything else" '
240619 16:15:51	INFO	'AdminPlugin: rule5      1 hour    \t"^3Rule #5: No offensive or potentially offensive names, annoying names, or in-game (double caret (^)) color in names" '
240619 16:15:51	INFO	'AdminPlugin: rule4      1 day     \t"^3Rule #4: No abusive language or behavior towards admins or other players" '
240619 16:15:51	INFO	'AdminPlugin: adv        1 day     \t"^3Rule #7: No advertising or spamming of websites or servers" '
240619 16:15:51	INFO	'AdminPlugin: afk        5 minutes \t"^7you appear to be away from your keyboard" '
240619 16:15:51	INFO	'AdminPlugin: generic    1 hour    \t"^7" '
240619 16:15:51	INFO	'AdminPlugin: ci         5 minutes \t"^7connection interupted, reconnect" '
240619 16:15:51	INFO	'AdminPlugin: racism     1.4 week  \t"^3Rule #1: No racism of any kind" '
240619 16:15:51	INFO	'AdminPlugin: camp       1 hour    \t"^7stop camping or you will be kicked!" '
240619 16:15:51	INFO	'AdminPlugin: sfire      3 hours   \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
240619 16:15:51	INFO	'AdminPlugin: color      1 hour    \t"^7No in-game (double caret (^)) color in names" '
240619 16:15:51	INFO	'AdminPlugin: tk         1 day     \t"^7stop team killing!" '
240619 16:15:51	INFO	'AdminPlugin: nocmd      1 hour    \t"^7do not use commands that you do not have access to, try using !help" '
240619 16:15:51	INFO	'AdminPlugin: spec       5 minutes \t"^7spectator too long on full server" '
240619 16:15:51	INFO	'AdminPlugin: lang       3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
240619 16:15:51	INFO	'AdminPlugin: cuss       3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
240619 16:15:51	INFO	'AdminPlugin: jerk       1 day     \t"^3Rule #4: No abusive language or behavior towards admins or other players" '
240619 16:15:51	INFO	'AdminPlugin: fakecmd    1 hour    \t"^7do not use fake commands" '
240619 16:15:51	INFO	'AdminPlugin: rule10     3 days    \t"^3Rule #10: Offense players must play for the objective and support their team" '
240619 16:15:51	INFO	'AdminPlugin: stack      1 day     \t"^3Rule #2: No clan stacking, members must split evenly between the teams" '
240619 16:15:51	INFO	'AdminPlugin: spawnfire  3 hours   \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
240619 16:15:51	INFO	'AdminPlugin: obj        1 hour    \t"^7go for the objective!" '
240619 16:15:51	INFO	'AdminPlugin: name       1 hour    \t"^3Rule #5: No offensive or potentially offensive names, annoying names, or in-game (double caret (^)) color in names" '
240619 16:15:51	INFO	'AdminPlugin: language   3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
240619 16:15:51	INFO	'AdminPlugin: default    1 hour    \t"^7behave yourself" '
240619 16:15:51	INFO	'AdminPlugin: profanity  3 days    \t"^3Rule #8: No profanity or offensive language (in any language)" '
240619 16:15:51	INFO	'AdminPlugin: spam       1 hour    \t"^7do not spam, shut-up!" '
240619 16:15:51	INFO	'AdminPlugin: recruit    1 day     \t"^3Rule #6: No recruiting for your clan, your server, or anything else" '
240619 16:15:51	INFO	'AdminPlugin: badname    1 hour    \t"^7No offensive, potentially offensive, or annoying names" '
240619 16:15:51	INFO	'AdminPlugin: spectator  5 minutes \t"^7spectator too long on full server" '
240619 16:15:51	INFO	'AdminPlugin: argue      1 day     \t"^3Rule #3: No arguing with admins (listen and learn or leave)" '
240619 16:15:51	INFO	'AdminPlugin: -------------- warn_reasons loaded ----------------'
240619 16:15:51	BOT    	'Attempting to connect to database b3'
240619 16:15:51	ERROR	'Error loading plugin admin'
Traceback (most recent call last):
  File "b3\parser.pyo", line 674, in loadPlugins
  File "b3\plugin.pyo", line 56, in __init__
  File "b3\plugin.pyo", line 115, in loadConfig
  File "b3\plugins\admin.pyo", line 163, in onLoadConfig
  File "b3\parser.pyo", line 895, in getGroupLevel
  File "b3\decorators.pyo", line 60, in __call__
  File "b3\parser.pyo", line 887, in getGroup
  File "b3\storage\database.pyo", line 858, in getGroup
AttributeError: 'NoneType' object has no attribute 'getOneRow'
240619 16:15:51	BOT    	'Loading Plugin #4 tk [conf\\plugin_tk.xml]'
240619 16:15:51	BOT    	'TkPlugin: Loading config conf\\plugin_tk.xml for TkPlugin'
240619 16:15:51	DEBUG	'TkPlugin: tk max level is 40'
240619 16:15:51	DEBUG	'TkPlugin: Send messages privately ? True'
240619 16:15:51	DEBUG	'TkPlugin: Damage Threshold is 100'
240619 16:15:51	DEBUG	'TkPlugin: TK Warning duration is 1h'
240619 16:15:51	DEBUG	'TkPlugin: Max warn level is 2'
240619 16:15:51	DEBUG	'TkPlugin: Half life for TK points is 0 (0 is disabled)'
240619 16:15:51	DEBUG	'TkPlugin: Using GAME_EXIT event to halve TK points'
240619 16:15:51	DEBUG	'Register Event: Stop Process: TkPlugin'
240619 16:15:51	DEBUG	'Register Event: Program Exit: TkPlugin'
240619 16:15:51	BOT    	'Plugin tk (1.2.8 - ThorN) loaded'
240619 16:15:51	BOT    	'Loading Plugin #5 stats [conf\\plugin_stats.xml]'
240619 16:15:51	BOT    	'StatsPlugin: Loading config conf\\plugin_stats.xml for StatsPlugin'
240619 16:15:51	DEBUG	'StatsPlugin: Using default value (0) for commands::mapstats'
240619 16:15:51	DEBUG	'StatsPlugin: Using default value (0) for commands::testscore'
240619 16:15:51	DEBUG	'StatsPlugin: Using default value (2) for commands::topstats'
240619 16:15:51	DEBUG	'Register Event: Stop Process: StatsPlugin'
240619 16:15:51	DEBUG	'Register Event: Program Exit: StatsPlugin'
240619 16:15:51	BOT    	'Plugin stats (1.3.7 - ThorN, GrosBedo) loaded'
240619 16:15:51	BOT    	'Loading Plugin #6 pingwatch [conf\\plugin_pingwatch.xml]'
240619 16:15:51	BOT    	'PingwatchPlugin: Loading config conf\\plugin_pingwatch.xml for PingwatchPlugin'
240619 16:15:51	VERBOSE	'Added crontab <bound method PingwatchPlugin.check of <b3.plugins.pingwatch.PingwatchPlugin instance at 0x0339CD00>> (54137616) - [0, 30]s -1m -1h -1d -1M -1DOW'
240619 16:15:51	ERROR	'Error loading plugin pingwatch'
Traceback (most recent call last):
  File "b3\parser.pyo", line 674, in loadPlugins
  File "b3\plugin.pyo", line 56, in __init__
  File "b3\plugin.pyo", line 115, in loadConfig
  File "b3\plugins\pingwatch.pyo", line 74, in onLoadConfig
AttributeError: 'NoneType' object has no attribute 'registerCommand'
240619 16:15:51	BOT    	'Loading Plugin #7 adv [conf\\plugin_adv.xml]'
240619 16:15:51	INFO	'cron scheduler started'
240619 16:15:51	BOT    	'AdvPlugin: Loading config conf\\plugin_adv.xml for AdvPlugin'
240619 16:15:51	INFO	'AdvPlugin: adv rate is 2'
240619 16:15:51	ERROR	'Error loading plugin adv'
Traceback (most recent call last):
  File "b3\parser.pyo", line 674, in loadPlugins
  File "b3\plugin.pyo", line 56, in __init__
  File "b3\plugin.pyo", line 115, in loadConfig
  File "b3\plugins\adv.pyo", line 154, in onLoadConfig
  File "b3\plugins\adv.pyo", line 219, in loadFromConfig
  File "b3\plugins\adv.pyo", line 228, in load
AttributeError: 'NoneType' object has no attribute 'getSpam'
240619 16:15:51	BOT    	'Loading Plugin #8 status [conf\\plugin_status.xml]'
240619 16:15:51	BOT    	'StatusPlugin: Loading config conf\\plugin_status.xml for StatusPlugin'
240619 16:15:51	DEBUG	'StatusPlugin: Using default table for saving server svars: current_svars'
240619 16:15:51	DEBUG	'StatusPlugin: Using default table for saving current clients: current_clients'
240619 16:15:51	VERBOSE	'Added crontab <bound method StatusPlugin.update of <b3.plugins.status.StatusPlugin instance at 0x033A30F8>> (55055440) - [0]s -1m -1h -1d -1M -1DOW'
240619 16:15:51	DEBUG	'Register Event: Stop Process: StatusPlugin'
240619 16:15:51	DEBUG	'Register Event: Program Exit: StatusPlugin'
240619 16:15:51	BOT    	'Plugin status (1.4.13 - ThorN) loaded'
240619 16:15:51	BOT    	'Loading Plugin #9 welcome [conf\\plugin_welcome.xml]'
240619 16:15:51	BOT    	'WelcomePlugin: Loading config conf\\plugin_welcome.xml for WelcomePlugin'
240619 16:15:51	INFO	'WelcomePlugin: delay set to 30. The bot will wait 30s after a player connects to write the welcome message'
240619 16:15:51	INFO	'WelcomePlugin: min_gap set to 3600. The bot will not welcome a player more than once every 3600 seconds'
240619 16:15:51	DEBUG	'Register Event: Stop Process: WelcomePlugin'
240619 16:15:51	DEBUG	'Register Event: Program Exit: WelcomePlugin'
240619 16:15:51	BOT    	'Plugin welcome (1.1 - ThorN) loaded'
240619 16:15:51	BOT    	'Loading Plugin #10 punkbuster [conf\\plugin_punkbuster.xml]'
240619 16:15:51	BOT    	'PunkbusterPlugin: Loading config conf\\plugin_punkbuster.xml for PunkbusterPlugin'
240619 16:15:51	VERBOSE	'Added crontab <bound method PunkbusterPlugin.rebuildBans of <b3.plugins.punkbuster.PunkbusterPlugin instance at 0x0348D030>> (55055728) - 0s 0m 0h -1d -1M -1DOW'
240619 16:15:51	DEBUG	'Register Event: Stop Process: PunkbusterPlugin'
240619 16:15:51	DEBUG	'Register Event: Program Exit: PunkbusterPlugin'
240619 16:15:51	BOT    	'Plugin punkbuster (1.1.0 - ThorN) loaded'
240619 16:15:51	BOT    	'Loading Plugin publist'
240619 16:15:51	BOT    	'PublistPlugin: No config file found for PublistPlugin. (was not required either)'
240619 16:15:51	DEBUG	'Register Event: Stop Process: PublistPlugin'
240619 16:15:51	DEBUG	'Register Event: Program Exit: PublistPlugin'
240619 16:15:51	BOT    	'Plugin publist (1.10.2 - ThorN, Courgette) loaded'
240619 16:15:51	DEBUG	'creating the event queue with size 50'
240619 16:15:51	BOT    	'Starting parser'
240619 16:15:51	DEBUG	'Client Connected: [-1] World - WORLD ({})'
240619 16:15:51	DEBUG	'Storage: getClient Client<@0:WORLD|WORLD:"World":-1>'
240619 16:15:51	BOT    	'Attempting to connect to database b3'
240619 16:15:51	DEBUG	"User not found WORLD: 'No client matching guid WORLD in admins_cache'"
240619 16:15:51	BOT    	'Client not found in the storage WORLD, create new'
240619 16:15:51	DEBUG	'Storage: setClient Client<@0:WORLD|WORLD:"World":-1>'
240619 16:15:51	DEBUG	"Storage: setClient data {'time_add': 1718824551, 'password': '', 'time_edit': 1718824551, 'name': 'World', 'group_bits': 0, 'ip': '', 'greeting': '', 'auto_login': 1, 'connections': 1, 'mask_level': 0, 'login': '', 'guid': 'WORLD', 'pbid': 'WORLD'}"
240619 16:15:51	BOT    	'Attempting to connect to database b3'
240619 16:15:51	DEBUG	'Client Authorized: [-1] World - WORLD'
240619 16:15:51	INFO	'map is: mp_paris'
240619 16:15:51	DEBUG	'Forcing server cvar g_logsync to 1'
240619 16:15:51	VERBOSE	"RCON sending (192.168.18.233:28960) 'set g_logsync 1'"
240619 16:15:52	VERBOSE	"RCON sending (192.168.18.233:28960) 'fs_game'"
240619 16:15:53	DEBUG	'Get cvar fs_game = ["fs_game" is: "^7" default: "^7"\n  Domain is any text\n]'
240619 16:15:53	VERBOSE	"RCON sending (192.168.18.233:28960) 'fs_basepath'"
240619 16:15:54	DEBUG	'Get cvar fs_basepath = ["fs_basepath" is: "C:\\MW2 iw4x_full_game^7" default: "C:\\MW2 iw4x_full_game^7"\n  Domain is any text\n]'
240619 16:15:54	DEBUG	'fs_basepath: C:\\MW2 iw4x_full_game'
240619 16:15:54	VERBOSE	"RCON sending (192.168.18.233:28960) 'fs_homepath'"
240619 16:15:54	DEBUG	'Get cvar fs_homepath = ["fs_homepath" is: "C:\\MW2 iw4x_full_game^7" default: "C:\\MW2 iw4x_full_game^7"\n  Domain is any text\n]'
240619 16:15:54	DEBUG	'fs_homepath: C:\\MW2 iw4x_full_game'
240619 16:15:54	VERBOSE	"RCON sending (192.168.18.233:28960) 'shortversion'"
240619 16:15:55	DEBUG	'Get cvar shortversion = ["shortversion" is: "r4528^7" default: "r4528^7"\n  Domain is any text\n]'
240619 16:15:55	DEBUG	'shortversion: r4528'
240619 16:15:55	DEBUG	'Parser started.'
240619 16:15:55	BOT    	'Starting plugins'
240619 16:15:55	VERBOSE	"RCON sending (192.168.18.233:28960) 'say ^0(^2b3^0)^7: ^8www.bigbrotherbot.net ^0(^8b3^0) ^9v1.9.2 [nt] ^9[^3PoisonIvy^9]^3 ^2[ONLINE]'"
240619 16:15:55	INFO	'STDOUT "Error: \'admin\'"'
240619 16:15:55	INFO	"STDOUT '\\n'"
240619 16:15:55	ERROR	"STDERR 'Traceback (most recent call last):\\n'"
240619 16:15:55	ERROR	'STDERR \'  File "b3\\\\__init__.pyo", line 182, in start\\n\''
240619 16:15:55	ERROR	'STDERR \'  File "b3\\\\parser.pyo", line 520, in start\\n\''
240619 16:15:55	ERROR	'STDERR \'  File "b3\\\\parser.pyo", line 780, in startPlugins\\n\''
240619 16:15:55	ERROR	'STDERR \'  File "b3\\\\parser.pyo", line 770, in start_plugin\\n\''
240619 16:15:55	ERROR	'STDERR "KeyError: \'admin\'\\n"'
240619 16:16:00	VERBOSE	"RCON sending (192.168.18.233:28960) 'status'"
240619 16:16:00	VERBOSE	'StatusPlugin: Building XML status'
240619 16:16:00	DEBUG	'StatusPlugin: Writing XML status to C:\\Users\\Administrador\\status.xml'
240619 16:16:05	BOT    	'Shutting down...'
240619 16:16:05	INFO	'StatusPlugin: B3 stop/exit.. updating status'
240619 16:16:05	DEBUG	'StatusPlugin: Writing XML status to C:\\Users\\Administrador\\status.xml'
240619 16:16:05	VERBOSE	'PunkbusterPlugin: Warning: No handle func for PunkbusterPlugin'
240619 16:16:05	BOT    	'Shutting down database connections...'

>

**Comment by michelszabo** [comment]
I'm using version 1.9.2, as I don't know how to configure the latest version.

**Comment by danielepantaleone** [comment]
It looks like you didn't configurale your database connection properly. Can you post your B3 configuration file?

**Comment by michelszabo** [comment]
I managed to make it work using XAMPP, but the commands are not working.
I am currently using the BigBrotherBot-1.9.2-win32 version, as I am unable to configure the latest version.
I'll post the entire folder, if you could look at it I'd appreciate it.

> It looks like you didn't configurale your database connection properly. Can you post your B3 configuration file?

[BigBrotherBot-1.9.2-win32.zip](https://github.com/user-attachments/files/15919063/BigBrotherBot-1.9.2-win32.zip)

**Comment by danielepantaleone** [comment]
The problem is that you are trying to use B3 on Call Of Duty MW2, but B3 does not support it. It supports Call of Duty 2 (which is the one you configured). Since B3 is a discontinued product I doubt someone will attempt to support new games, unless the request is very high and someone wants to jump in B3 development.

**Comment by michelszabo** [comment]
Strange because I already used B3 on an MW2 server years ago.
At https://github.com/BigBrotherBot/big-brother-bot it says it supports Call of Duty 6: Modern Warfare 2

**Comment by danielepantaleone** [comment]
I thought you were referring to [this game](https://en.m.wikipedia.org/wiki/Call_of_Duty:_Modern_Warfare_II_(2022_video_game)). Anyway, yes Call of duty 6 is supported. You have to specify "cod6" as game parser in your b3.xml and not "cod2".

**Comment by michelszabo** [comment]
![iw4x](https://github.com/BigBrotherBot/big-brother-bot/assets/173087762/05d0fcbe-c63c-4500-813b-66c22d0cd494)
I use the commands !b3, !status etc and nothing works.
But B3 messages are working on the server.
I configured it as cod6 but it is not working.

**Comment by michelszabo** [comment]
I managed to solve it, thank you.
The solution was b3.xml from this topic https://github.com/BigBrotherBot/big-brother-bot/issues/407
