### ISSUE TITLE
Create Discussions section?

### ISSUE THREAD

**Issue by grb-ani** [BigBrotherBot/big-brother-bot#435]
Hello, since the forum is no longer available would you consider opening a [Discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions) section for this repository? Perhaps there are questions or advice people wish to contribute that don't really belong in an Issue tracker, for example [this post](https://github.com/BigBrotherBot/big-brother-bot/issues/407) offering a Docker image with the latest b3 version.

**Comment by danielepantaleone** [comment]
Indeed we could. I don't have enough time to look into this right now, maybe someone else could help though.

**Comment by danielepantaleone** [comment]
@veiled-bird I have enabled the discussion section: https://github.com/BigBrotherBot/big-brother-bot/discussions
