### ISSUE TITLE
simple Dialog

### ISSUE THREAD

**Issue by ozon** [BigBrotherBot/big-brother-bot#48]
I miss a simple dialog system. This would simplify the use dramatically. For example, I load a new card and write the map name wrong. B3 are indeed suggestions, but B3 might also ask whether the proposal should be used.

Another example would be confirmation questions.
User: ```/die```
B3: ```Would you shut down really B3? (yes / no / cancel)```
User: ```/yes```

You can implement something locally in that cmd. But it would be very useful if a function would be generally available so that eg Plugin developers benefit. Before now implemented this feature, which would be taken into consideration?

I am thinking of the following:
- session system with timeout
- B3 should blocked while waiting for a response (session enough or is threading needed?
- API design
```
  b3_dialog_question(question, options)
  ```

It is sometimes frustrating when you're in the rush enter a wrong command, B3 makes a proposal and then re-enter the command. (Even worse, you are in command again incorrectly :)) Confirmation dialogs for some commands are well protected against accidental incorrect entries.

**Comment by danielepantaleone** [comment]
I don't seem to see this as doable for B3 nor I think it will be useful, so for the moment I'll close this one. We can open the discussion again if someone is in need of this feature.
